import {_electron,expect,test,type ElectronApplication,type Page} from '@playwright/test';
import fs from 'node:fs/promises';import path from 'node:path';import {DocumentStore} from '../../src/main/storage';
let app:ElectronApplication,page:Page,root:string;
async function launch(file:string){const env:NodeJS.ProcessEnv={...process.env,TODOLINE_TEST:'1',TODOLINE_DATA_DIR:path.join(root,'profile')};delete env.ELECTRON_RUN_AS_NODE;const executablePath=process.env.TODOLINE_TEST_EXE;app=await _electron.launch({...(executablePath?{executablePath,args:[file]}:{args:[path.resolve('.'),file]}),env:env as Record<string,string>});page=await app.firstWindow();await expect(page.locator('.document-scroller[data-active] .ProseMirror')).toBeVisible();}
const body=()=>page.locator('.document-scroller[data-active] .ProseMirror');
test.beforeEach(async({},info)=>{test.setTimeout(90000);root=info.outputPath('workspace');await fs.mkdir(root,{recursive:true});});
test.afterEach(async()=>{await app?.evaluate(({app})=>app.exit(0)).catch(()=>{});});
async function fixture(ext:string,text:string){const file=path.join(root,'文档.'+ext);if(ext==='tde'){const store=new DocumentStore(),doc=store.open(file,true);await store.save({...doc,events:[{id:-1,pos:0,created_at:1700000000,deadline_raw:'',deadline_ts:null,done:0,top_divider:0,content_text:text,content_html:`<p>${text}</p>`}]});store.close(doc.handle);}else await fs.writeFile(file,text);return file;}
async function drag(from:number,to:number,ctrl=false){const points=await body().locator('p').first().evaluate((p,{from,to})=>{const walker=document.createTreeWalker(p,NodeFilter.SHOW_TEXT),nodes:Text[]=[];let n;while(n=walker.nextNode())nodes.push(n as Text);const rect=(offset:number)=>{for(const node of nodes){if(offset<=node.length){const r=document.createRange();r.setStart(node,offset);r.collapse(true);const b=r.getBoundingClientRect();return {x:b.x,y:b.y+b.height/2};}offset-=node.length;}throw Error('offset');};return [rect(from),rect(to)];},{from,to});if(ctrl)await page.keyboard.down('Control');await page.mouse.move(points[0].x,points[0].y);await page.mouse.down();await page.mouse.move(points[1].x,points[1].y,{steps:6});await page.mouse.up();if(ctrl)await page.keyboard.up('Control');}
for(const ext of ['txt','md','tde'])test(ext+' supports Ctrl disjoint copy, deletion, typing and undo',async()=>{
 await launch(await fixture(ext,'alpha keep omega'));await drag(0,5);await drag(11,16,true);const selected=body().locator('.multi-text-selection,.column-selection');await expect(selected).toHaveCount(2);
 await page.keyboard.press('Control+c');await expect.poll(()=>app.evaluate(({clipboard})=>clipboard.readText()),{timeout:15000}).toBe('alpha\nomega');
 await page.keyboard.press('Delete');await expect(body().locator('p').first()).toHaveText(' keep ');await page.keyboard.press('Control+z');await expect(body().locator('p').first()).toHaveText('alpha keep omega');
 await drag(0,5);await drag(11,16,true);await page.keyboard.insertText('X');await expect(body().locator('p').first()).toHaveText('X keep X');await page.keyboard.press('Control+z');await expect(body().locator('p').first()).toHaveText('alpha keep omega');
 await drag(0,5);await drag(11,16,true);await page.keyboard.press('Control+x');await expect.poll(()=>app.evaluate(({clipboard})=>clipboard.readText()),{timeout:15000}).toBe('alpha\nomega');await expect(body().locator('p').first()).toHaveText(' keep ');
});
test('plain text blank canvas click focuses the first line or end of existing content',async()=>{
 const file=await fixture('txt','');await launch(file);const canvas=page.locator('.document-scroller[data-active]');await canvas.click({position:{x:300,y:350}});await expect(body()).toBeFocused();await page.keyboard.insertText('first\nlast');await expect(body()).toContainText('last');await page.keyboard.press('Control+Home');await canvas.click({position:{x:300,y:350}});await expect(body()).toBeFocused();await page.keyboard.insertText(' END');await expect.poll(()=>fs.readFile(file,'utf8')).toBe('first\nlast END');
});
test('line spacing matches across modes, settings persist, and recent right click only reveals the path',async()=>{
 const file=await fixture('txt','first\nsecond');await launch(file);expect(await body().evaluate(el=>getComputedStyle(el).lineHeight)).toBe('22.5px');
 await page.getByRole('button',{name:'打开设置菜单'}).click();await page.getByRole('spinbutton',{name:'正文行距'}).fill('1.8');await page.keyboard.press('Escape');await expect.poll(()=>body().evaluate(el=>getComputedStyle(el).lineHeight)).toBe('27px');
 for(const ext of ['md','tde']){const next=await fixture(ext,'first\nsecond');await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},next);await page.getByRole('button',{name:'打开文档 · Ctrl+O',exact:true}).click();await expect(body()).toHaveClass(ext==='md'?/markdown-document/:/todo-document/);expect(await body().evaluate(el=>getComputedStyle(el).lineHeight)).toBe('27px');}
 const tabs=await page.locator('.file-tab').count();await app.evaluate(({shell})=>{shell.showItemInFolder=file=>{(globalThis as any).revealed=file;};});await page.getByRole('button',{name:'最近打开的文档',exact:true}).click();const recent=page.locator('.recent-items>button').filter({hasText:'文档.txt'});await recent.click({button:'right'});expect(await app.evaluate(()=> (globalThis as any).revealed)).toBe(file);await expect(page.locator('.file-tab')).toHaveCount(tabs);await page.keyboard.press('Escape');
 await app.evaluate(({app})=>app.exit(0));await launch(file);expect(await body().evaluate(el=>getComputedStyle(el).lineHeight)).toBe('27px');
});
test('Ctrl click adds and toggles words, and right clicking any selected range keeps the whole selection',async()=>{
 await launch(await fixture('md','alpha keep omega'));await drag(1,1,true);await drag(12,12,true);await expect(body().locator('.multi-text-selection')).toHaveCount(2);
 await body().locator('.multi-text-selection').last().click({button:'right'});await page.getByRole('menuitem',{name:'复制 Ctrl C',exact:true}).click();await expect.poll(()=>app.evaluate(({clipboard})=>clipboard.readText()),{timeout:15000}).toBe('alpha\nomega');
 await drag(1,1,true);await expect(body().locator('.multi-text-selection')).toHaveCount(1);await expect(body().locator('.multi-text-selection')).toHaveText('omega');await page.keyboard.press('Escape');await expect(body().locator('.multi-text-selection')).toHaveCount(0);
});
