import {_electron,expect,test,type ElectronApplication,type Page} from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import Database from 'better-sqlite3';
import {DocumentStore} from '../../src/main/storage';
import {clipboardPacket} from '../../src/main/clipboard-format';
let app:ElectronApplication,page:Page,root:string,file:string,other:string;
const editor=()=>page.locator('.document-scroller:visible .todo-document');
const qtEnv=()=>({...process.env,QT_QPA_PLATFORM:'windows',PATH:'E:\\Qt\\6.8.3\\mingw_64\\bin;E:\\Qt\\Tools\\mingw1310_64\\bin;'+process.env.PATH});
function saved(target=file){const db=new Database(target,{readonly:true});try{return {events:db.prepare('select * from events order by pos').all() as any[],assets:db.prepare('select * from assets order by id').all() as any[]};}finally{db.close();}}
const event=(html:string,text:string)=>({created_at:1750000000,deadline_raw:'明天',deadline_ts:1750089600,done:true,top_divider:true,html,text});
function clipboard(payload:unknown){execFileSync(path.resolve('out/main/clipboard-win.exe'),{input:clipboardPacket([{name:'CF_UNICODETEXT',data:Buffer.from('\0','utf16le')},{name:'application/x-tde-events',data:Buffer.from(JSON.stringify(payload))}]),windowsHide:true});}
async function png(){return Buffer.from(await app.evaluate(({nativeImage})=>{const pixels=Buffer.alloc(32*24*4);for(let i=0;i<pixels.length;i+=4){pixels[i]=30;pixels[i+1]=80;pixels[i+2]=180;pixels[i+3]=255;}return Array.from(nativeImage.createFromBitmap(pixels,{width:32,height:24}).toPNG());}));}
const asset=(data:Buffer,id=1)=>({name:`asset:${id}`,data:data.toString('base64'),w:32,h:24});
async function qtCopy(payload:unknown){const input=path.join(root,'qt-in.json'),output=path.join(root,'qt-out.json');await fs.writeFile(input,JSON.stringify(payload));execFileSync(path.resolve('.cache/qt-compat/qt-compat.exe'),['clipboard',input,output],{windowsHide:true,env:qtEnv()});expect(await app.evaluate(({clipboard})=>clipboard.readBuffer('application/x-tde-events').length)).toBeGreaterThan(0);}
test.beforeEach(async({},info)=>{root=info.outputPath('workspace');await fs.mkdir(root,{recursive:true});file=path.join(root,'事件资产.tde');other=path.join(root,'另一个文件.tde');const store=new DocumentStore();for(const target of [file,other]){const doc=store.open(target,true);await store.save({...doc,events:[{id:-1,pos:0,created_at:1750000000,deadline_raw:'',deadline_ts:null,done:0,top_divider:0,content_html:'<p>abcdef</p>',content_text:'abcdef'}]});store.close(doc.handle);}const env:NodeJS.ProcessEnv={...process.env,TODOLINE_TEST:'1',TODOLINE_DATA_DIR:path.join(root,'profile')};delete env.ELECTRON_RUN_AS_NODE;app=await _electron.launch({args:[path.resolve('.'),'--open',file],env:env as Record<string,string>});page=await app.firstWindow();await app.evaluate(({BrowserWindow})=>{BrowserWindow.getAllWindows()[0].show();BrowserWindow.getAllWindows()[0].focus();});await expect(editor()).toBeVisible();await editor().evaluate((el:any)=>{el.editor.commands.setTextSelection(3);el.editor.view.focus();});});
test.afterEach(async({},info)=>{if(info.status!==info.expectedStatus)await page?.screenshot({path:info.outputPath('failure.png')}).catch(()=>{});await app?.evaluate(({app})=>app.exit(0)).catch(()=>{});});
test('actual Qt events retain literal asset text, metadata and one shared original image through SQLite and undo',async({},info)=>{const bytes=await png();await page.keyboard.press('Control+a');await qtCopy({events:[event('<p><b>asset:1 正文</b><img src="asset:1" width="16" height="12" /></p>','asset:1 正文[图片]'),event('<p>第二项<img src="asset:1" width="8" height="6" /></p>','第二项[图片]')],assets:[asset(bytes),asset(Buffer.from('unused invalid bytes'),9)]});await page.keyboard.press('Control+v');await expect(editor().locator('.image-view')).toHaveCount(2);await expect(editor().locator('strong')).toHaveText('asset:1 正文');await expect.poll(()=>saved().events.length).toBe(2);const state=saved();expect(state.assets).toHaveLength(1);expect(Buffer.from(state.assets[0].data)).toEqual(bytes);expect(state.events[0]).toMatchObject({created_at:1750000000,deadline_raw:'明天',deadline_ts:1750089600,done:1,top_divider:1});await page.screenshot({path:info.outputPath('qt-event-assets.png')});await page.keyboard.press('Control+z');await expect(editor()).toHaveText('abcdef');await expect.poll(()=>saved().events[0].content_text).toBe('abcdef');await page.keyboard.press('Control+y');await expect(editor().locator('.image-view')).toHaveCount(2);});
test('a corrupt later event image adds no assets and preserves the selected document for retry',async()=>{const bytes=await png();await page.keyboard.press('Control+a');const payload={events:[event('<p><img src="asset:1" /><img src="asset:2" /></p>','[图片][图片]')],assets:[asset(bytes),asset(Buffer.from('bad image'),2)]};clipboard(payload);await page.keyboard.press('Control+v');await expect(page.locator('.toast')).toContainText('asset:2');await expect(editor()).toHaveText('abcdef');expect(saved().assets).toHaveLength(0);await page.getByRole('button',{name:'关闭消息'}).click();await editor().focus();clipboard({...payload,assets:[asset(bytes),asset(bytes,2)]});await page.keyboard.press('Control+v');await expect(editor().locator('.image-view')).toHaveCount(2);await expect.poll(()=>saved().assets.length).toBe(2);await page.keyboard.press('Control+z');await expect(editor()).toHaveText('abcdef');});
test('a missing fragment reference is reported before any image is saved',async()=>{const bytes=await png();await page.keyboard.press('Control+a');clipboard({fragment:[{type:'paragraph',content:[{type:'text',text:'asset:1'},{type:'image',attrs:{assetId:1,width:16,height:12}},{type:'image',attrs:{assetId:99}}]}],assets:[asset(bytes)]});await page.keyboard.press('Control+v');await expect(page.locator('.toast')).toContainText('缺少原图');await expect(editor()).toHaveText('abcdef');expect(saved().assets).toHaveLength(0);});
test('full-event copy remaps actual images across files without altering text, links or original pixels',async()=>{const bytes=await png();await page.keyboard.press('Control+a');clipboard({events:[event('<p>asset:1 <a href="https://example.com/asset:1">链接 asset:1</a><img src="asset:1" width="16" height="12" /></p>','asset:1 链接 asset:1[图片]')],assets:[asset(bytes)]});await page.keyboard.press('Control+v');await expect(editor().locator('.image-view')).toHaveCount(1);await expect.poll(()=>saved().assets.length).toBe(1);await page.keyboard.press('Control+a');await app.evaluate(({clipboard})=>clipboard.clear());await page.keyboard.press('Control+c');await expect.poll(()=>app.evaluate(({clipboard})=>clipboard.readBuffer('application/x-tde-events').toString())).toContain('asset:1');const store=new DocumentStore(),doc=store.open(other);await store.addAsset(doc.handle,bytes,32,24);store.close(doc.handle);await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},other);await page.getByRole('button',{name:'打开文档 · Ctrl+O',exact:true}).click();await expect(page.locator('.file-tab')).toHaveCount(2);await editor().focus();await page.keyboard.press('Control+a');await page.keyboard.press('Control+v');await expect(editor().locator('.image-view')).toHaveCount(1);await expect(editor()).toContainText('asset:1');await expect(editor().locator('a')).toHaveAttribute('href','https://example.com/asset:1');await expect.poll(()=>saved(other).events[0].content_html).toContain('src="asset:2"');expect(saved(other).events[0].content_text).toContain('asset:1');expect(Buffer.from(saved(other).assets[1].data)).toEqual(bytes);});
test('literal asset text copies and exports to Chinese PDF without becoming a resource URL',async()=>{const bytes=await png();await page.keyboard.press('Control+a');clipboard({events:[event('<p>正文 asset:999<img src="asset:1" width="16" height="12" /></p>','正文 asset:999[图片]')],assets:[asset(bytes)]});await page.keyboard.press('Control+v');await expect(editor()).toContainText('asset:999');await expect(editor().locator('.image-view')).toHaveCount(1);await expect.poll(()=>saved().events[0].content_text).toContain('asset:999');await page.keyboard.press('Control+a');await page.keyboard.press('Control+c');await expect.poll(()=>app.evaluate(({clipboard})=>clipboard.readText())).toContain('asset:999');const out=path.join(root,'引用文字.pdf');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},out);await page.getByRole('button',{name:'导出',exact:true}).click();await page.getByRole('button',{name:'PDF 文档 .pdf',exact:true}).click();await expect.poll(async()=>fs.stat(out).then(s=>s.size,()=>0)).toBeGreaterThan(500);await expect(page.getByRole('dialog',{name:'导出完成'})).toContainText('引用文字.pdf');});
test('invalid later event metadata and conflicting image IDs preserve the document without asset writes',async()=>{const bytes=await png();for(const payload of [{events:[event('<p><img src="asset:1" /></p>','[图片]'),{...event('<p>x</p>','x'),created_at:'invalid'}],assets:[asset(bytes)]},{events:[event('<p><img src="asset:1" /></p>','[图片]')],assets:[asset(bytes),{...asset(Buffer.from('different')),name:'asset:01'}]}]){await editor().focus();await page.keyboard.press('Control+a');clipboard(payload);await page.keyboard.press('Control+v');await expect(page.locator('.toast')).toBeVisible();await expect(editor()).toHaveText('abcdef');expect(saved().assets).toHaveLength(0);await page.getByRole('button',{name:'关闭消息'}).click();}});
test('Qt edits the saved shared images without changing literal text or original bytes',async()=>{const bytes=await png();await page.keyboard.press('Control+a');await qtCopy({events:[event('<p>asset:1<img src="asset:1" width="16" height="12" /></p>','asset:1[图片]')],assets:[asset(bytes)]});await page.keyboard.press('Control+v');await expect(editor().locator('.image-view')).toHaveCount(1);await expect.poll(()=>saved().events[0].content_html).toContain('asset:1');await page.locator('.file-tab.active .tab-close').click();await expect(page.locator('.file-tab')).toHaveCount(0);execFileSync(path.resolve('.cache/qt-compat/qt-compat.exe'),['edit',file],{windowsHide:true,env:{...qtEnv(),QT_QPA_PLATFORM:'offscreen'}});await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},file);await page.getByRole('button',{name:'打开文档 · Ctrl+O',exact:true}).click();await expect(editor()).toContainText('asset:1');await expect(editor()).toContainText('旧版再次编辑');await expect(editor().locator('.image-view')).toHaveCount(1);expect(Buffer.from(saved().assets[0].data)).toEqual(bytes);});
test('native copying of partial ordered and nested lists keeps selected text and numbering',async({},info)=>{for(const nested of [false,true]){await app.evaluate(({clipboard},html)=>{clipboard.clear();clipboard.writeHTML(html);},nested?'<ul><li><p>outer</p><ul><li><p>inner</p></li></ul></li><li><p>ending</p></li></ul>':'<ol start="3"><li>aaa</li><li>bbb</li><li>ccc</li></ol>');await editor().focus();await page.keyboard.press('Control+a');await page.keyboard.press('Control+v');await expect(editor()).toContainText(nested?'ending':'ccc');await editor().evaluate((el:any,nested)=>{let from=0,to=0;el.editor.state.doc.descendants((n:any,p:number)=>{if(n.isText&&n.text===(nested?'inner':'bbb'))from=p+1;if(n.isText&&n.text===(nested?'ending':'ccc'))to=p+2;});el.editor.commands.setTextSelection({from,to});el.editor.view.focus();},nested);await app.evaluate(({clipboard})=>clipboard.clear());await page.keyboard.press('Control+c');await expect.poll(()=>app.evaluate(({clipboard})=>clipboard.readBuffer('application/x-tde-events').length)).toBeGreaterThan(0);await page.getByRole('button',{name:'新建文档 · Ctrl+N',exact:true}).click();await expect(editor()).not.toContainText(nested?'outer':'aaa');await editor().focus();await page.keyboard.press('Control+v');await expect(editor()).toContainText(nested?'nner':'bb');await expect(editor()).not.toContainText(nested?'outer':'aaa');if(!nested){await expect(editor().locator('ol')).toHaveAttribute('start','4');await expect(editor().locator('ol > li')).toHaveText(['bb','cc']);}else{await expect(editor().locator('ul > li').last()).toHaveText('en');await expect(editor().locator('ul ul li')).toHaveText('nner');}await page.screenshot({path:info.outputPath(nested?'nested-fragment.png':'ordered-fragment.png')});await page.keyboard.press('Control+z');await expect(editor()).toHaveText('');}});
