import {_electron,expect,test,type ElectronApplication,type Page} from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import Database from 'better-sqlite3';
import {DocumentStore} from '../../src/main/storage';
let app:ElectronApplication,page:Page,root:string,file:string;
const editor=()=>page.locator('.document-scroller:visible .todo-document');
function rows(target=file){const db=new Database(target,{readonly:true});try{return db.prepare('select * from events order by pos').all() as any[];}finally{db.close();}}
async function seed(target:string,texts=['甲','乙','丙','丁']){const store=new DocumentStore(),doc=store.open(target,true);await store.save({...doc,events:texts.map((text,i)=>({id:-i-1,pos:i*1024,created_at:1750000000+i,deadline_raw:'',deadline_ts:null,done:i%2,top_divider:1,content_html:`<p>${text}</p>`,content_text:text}))});store.close(doc.handle);}
async function select(indices:number[]){for(const [i,index] of indices.entries())await editor().locator('.event-divider').nth(index).locator('.divider-stroke').first().click({modifiers:i?['Control']:[]});await expect(page.locator('.selection-count')).toHaveText(`已选 ${indices.length} 个事件`);}
test.beforeEach(async({},info)=>{root=info.outputPath('workspace');await fs.mkdir(root,{recursive:true});file=path.join(root,'事件选择.tde');await seed(file);const env:NodeJS.ProcessEnv={...process.env,TODOLINE_TEST:'1',TODOLINE_DATA_DIR:path.join(root,'profile')};delete env.ELECTRON_RUN_AS_NODE;app=await _electron.launch({args:[path.resolve('.'),'--open',file],env:env as Record<string,string>});page=await app.firstWindow();await app.evaluate(({BrowserWindow})=>{BrowserWindow.getAllWindows()[0].show();BrowserWindow.getAllWindows()[0].focus();});await expect(editor()).toBeVisible();});
test.afterEach(async({},info)=>{if(info.status!==info.expectedStatus)await page?.screenshot({path:info.outputPath('failure.png')}).catch(()=>{});await app?.evaluate(({app})=>app.exit(0)).catch(()=>{});});
for(const selected of [[1,2],[0,2]])test(`plain event-selection paste matches actual Qt ordering for ${selected.join(',')} and undoes after saving`,async()=>{
  const qt=path.join(root,'Qt.tde'),request=path.join(root,'request.json');await seed(qt);await fs.writeFile(request,JSON.stringify({selected,text:'新内容'}));const expected=JSON.parse(execFileSync(path.resolve('.cache/qt-compat/qt-compat.exe'),['paste-selection',qt,request],{windowsHide:true,encoding:'utf8',env:{...process.env,QT_QPA_PLATFORM:'offscreen',PATH:'E:\\Qt\\6.8.3\\mingw_64\\bin;E:\\Qt\\Tools\\mingw1310_64\\bin;'+process.env.PATH}})).map((e:any)=>e.text);
  const before=rows();await select(selected);await app.evaluate(({clipboard})=>{clipboard.clear();clipboard.writeText('新内容');});await page.keyboard.press('Control+v');await expect.poll(()=>rows().map(e=>e.content_text)).toEqual(expected);await expect(page.locator('.selection-count')).toHaveCount(0);await page.keyboard.press('Control+z');await expect.poll(()=>rows().map(e=>[e.id,e.content_text,e.created_at,e.done])).toEqual(before.map(e=>[e.id,e.content_text,e.created_at,e.done]));
});
test('native fragment clipboard replaces events with its metadata and survives Qt reopening',async()=>{
  const payload={fragment:[{type:'paragraph',content:[{type:'text',text:'新内容',marks:[{type:'bold'}]}]}],events:[{created_at:1750001234,deadline_raw:'明天',deadline_ts:1750999999,done:true,top_divider:true,html:'<p><b>新内容</b></p>',text:'新内容'}],assets:[]};await app.evaluate(({clipboard},payload)=>{clipboard.clear();clipboard.writeBuffer('application/x-tde-events',Buffer.from(JSON.stringify(payload)));},payload);await select([1,2]);await page.keyboard.press('Control+v');await expect.poll(()=>rows().map(e=>e.content_text)).toEqual(['甲','新内容','丁']);expect(rows()[1]).toMatchObject({created_at:1750001234,deadline_raw:'明天',deadline_ts:1750999999,done:1});await expect(editor().locator('strong')).toHaveText('新内容');await page.locator('.file-tab.active .tab-close').click();await expect(page.locator('.file-tab')).toHaveCount(0);
  execFileSync(path.resolve('.cache/qt-compat/qt-compat.exe'),['edit',file],{windowsHide:true,env:{...process.env,QT_QPA_PLATFORM:'offscreen',PATH:'E:\\Qt\\6.8.3\\mingw_64\\bin;E:\\Qt\\Tools\\mingw1310_64\\bin;'+process.env.PATH}});expect(rows()[1]).toMatchObject({created_at:1750001234,deadline_raw:'明天',deadline_ts:1750999999,done:1});expect(rows()[1].content_text).toContain('新内容');
});
test('file-picker images replace selected events atomically and restore original bodies in one undo',async({},info)=>{
  const png=Buffer.from(await app.evaluate(({nativeImage})=>Array.from(nativeImage.createFromBitmap(Buffer.alloc(80*60*4,255),{width:80,height:60}).toPNG())));await select([1,2]);await page.locator('input[type=file]').setInputFiles([{name:'一.png',mimeType:'image/png',buffer:png},{name:'二.png',mimeType:'image/png',buffer:png}]);await expect(editor().locator('.image-view')).toHaveCount(2);await expect.poll(()=>rows().length).toBe(3);expect(rows().map(e=>e.content_text).filter(t=>t==='乙'||t==='丙')).toEqual([]);const db=new Database(file,{readonly:true});try{const assets=db.prepare('select * from assets order by id').all() as any[];expect(assets).toHaveLength(2);assets.forEach(a=>expect(Buffer.from(a.data)).toEqual(png));}finally{db.close();}await page.screenshot({path:info.outputPath('event-images.png')});await page.keyboard.press('Control+z');await expect.poll(()=>rows().map(e=>e.content_text)).toEqual(['甲','乙','丙','丁']);await expect(editor().locator('.image-view')).toHaveCount(0);
});
test('noncontiguous paste replaces the empty final event just as Qt does',async()=>{
  await editor().locator('p').last().click();await page.keyboard.press('End');await page.keyboard.press('Backspace');await expect.poll(()=>rows().at(-1).content_text).toBe('');const qt=path.join(root,'Qt-empty.tde'),request=path.join(root,'request.json');await seed(qt,['甲','乙','丙','']);await fs.writeFile(request,JSON.stringify({selected:[0,2],text:'新内容'}));const expected=JSON.parse(execFileSync(path.resolve('.cache/qt-compat/qt-compat.exe'),['paste-selection',qt,request],{windowsHide:true,encoding:'utf8',env:{...process.env,QT_QPA_PLATFORM:'offscreen',PATH:'E:\\Qt\\6.8.3\\mingw_64\\bin;E:\\Qt\\Tools\\mingw1310_64\\bin;'+process.env.PATH}})).map((e:any)=>e.text);
  await select([0,2]);await app.evaluate(({clipboard})=>{clipboard.clear();clipboard.writeText('新内容');});await page.keyboard.press('Control+v');await expect.poll(()=>rows().map(e=>e.content_text)).toEqual(expected);expect(expected).toEqual(['甲','乙','丙','新内容']);
});
test('system image clipboard replaces a complete first event, preserving pixels and following IDs',async()=>{
  const before=rows(),png=await app.evaluate(({clipboard,nativeImage})=>{const image=nativeImage.createFromBitmap(Buffer.alloc(80*60*4,255),{width:80,height:60});clipboard.clear();clipboard.writeImage(image);return Array.from(clipboard.readImage().toPNG());});await select([0]);await page.keyboard.press('Control+v');await expect(editor().locator('.image-view')).toHaveCount(1);await expect.poll(()=>rows()[0].content_html).toContain('asset:');expect(rows()[0].content_text).not.toContain('甲');expect(rows().slice(1).map(e=>e.id)).toEqual(before.slice(1).map(e=>e.id));const db=new Database(file,{readonly:true});try{const asset=db.prepare('select * from assets order by id desc limit 1').get() as any;expect([asset.w,asset.h]).toEqual([80,60]);expect(Buffer.from(asset.data)).toEqual(Buffer.from(png));}finally{db.close();}await page.keyboard.press('Control+z');await expect.poll(()=>rows().map(e=>e.id)).toEqual(before.map(e=>e.id));
});
