import {_electron,expect,test,type ElectronApplication,type Page} from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import Database from 'better-sqlite3';
import {DocumentStore} from '../../src/main/storage';
let app:ElectronApplication,page:Page,root:string,file:string;
const editor=()=>page.locator('.document-scroller:visible .todo-document');
function saved(){const db=new Database(file,{readonly:true});try{return db.prepare('select * from events order by pos').all() as any[];}finally{db.close();}}
async function caret(text:string,offset=0){await editor().evaluate((el:any,args)=>{let found=-1;el.editor.state.doc.descendants((n:any,p:number)=>{if(n.isText&&n.text===args.text)found=p+args.offset;});if(found<0)throw new Error('Text missing');el.editor.commands.setTextSelection(found);el.editor.commands.focus();},{text,offset});await expect(editor()).toBeFocused();}
async function valid(){await editor().evaluate((el:any)=>{el.editor.state.doc.check();el.editor.state.doc.descendants((n:any,_p:number,parent:any)=>{if(n.type.name==='divider'&&parent.type.name!=='doc')throw new Error('Nested event boundary');});});}
test.beforeEach(async({},info)=>{
  root=info.outputPath('workspace');await fs.mkdir(root,{recursive:true});file=path.join(root,'嵌套事件.tde');const store=new DocumentStore(),doc=store.open(file,true);
  await store.save({...doc,events:[{id:-1,pos:1024,created_at:1750000000,deadline_raw:'旧截止',deadline_ts:1750086400,done:1,top_divider:0,content_html:'<ol start="5"><li>前文</li><li><p>甲乙丙丁</p><blockquote><p>引用正文</p></blockquote></li><li>后文</li></ol>',content_text:'前文甲乙丙丁引用正文后文'}]});store.close(doc.handle);
  const env:NodeJS.ProcessEnv={...process.env,TODOLINE_TEST:'1',TODOLINE_DATA_DIR:path.join(root,'profile')};delete env.ELECTRON_RUN_AS_NODE;
  app=await _electron.launch({args:[path.resolve('.'),'--open',file],env:env as Record<string,string>});page=await app.firstWindow();await app.evaluate(({BrowserWindow})=>{BrowserWindow.getAllWindows()[0].show();BrowserWindow.getAllWindows()[0].focus();});await expect(editor()).toBeVisible();
});
test.afterEach(async({},info)=>{if(info.status!==info.expectedStatus)await page?.screenshot({path:info.outputPath('failure.png')}).catch(()=>{});await app?.evaluate(({app})=>app.exit(0)).catch(()=>{});});
test('Ctrl+H splits a list into independent events with continued numbering and Qt roundtrip',async({},info)=>{
  const original=saved()[0];await caret('甲乙丙丁',2);await page.keyboard.press('Control+h');await valid();await expect(editor().locator(':scope > .event-divider')).toHaveCount(1);await expect(editor().locator(':scope > ol')).toHaveCount(2);await expect(editor().locator(':scope > ol').nth(1)).toHaveAttribute('start','6');await expect(editor().locator(':scope > ol').first()).toHaveClass(/done-content/);
  await expect.poll(()=>saved().length).toBe(2);expect(saved()[0]).toMatchObject({id:original.id,created_at:original.created_at,done:1,deadline_raw:'旧截止',deadline_ts:1750086400});expect(saved()[1]).toMatchObject({done:0,deadline_raw:'',deadline_ts:null});expect(saved()[0].content_text).toContain('甲乙');expect(saved()[1].content_text).toContain('丙丁');await page.screenshot({path:info.outputPath('nested-split.png')});
  await page.locator('.file-tab.active .tab-close').click();execFileSync(path.resolve('.cache/qt-compat/qt-compat.exe'),['edit',file],{windowsHide:true,env:{...process.env,QT_QPA_PLATFORM:'offscreen',PATH:'E:\\Qt\\6.8.3\\mingw_64\\bin;E:\\Qt\\Tools\\mingw1310_64\\bin;'+process.env.PATH}});await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},file);await page.getByRole('button',{name:'打开文档 · Ctrl+O',exact:true}).click();await expect(editor()).toContainText('旧版再次编辑');await expect(editor().locator('.legacy-content')).toHaveCount(0);await valid();expect(saved()).toHaveLength(2);expect(saved()[1].content_html).toContain('start="6"');
});
test('leading list divider deletes with usual keys and undo restores exact metadata',async()=>{
  const original=saved()[0];await caret('前文');await page.keyboard.press('Control+h');await expect(editor().locator('.event-divider')).toHaveCount(1);await expect.poll(()=>saved()[0].top_divider).toBe(1);await page.keyboard.press('Control+z');await expect.poll(()=>saved()[0].top_divider).toBe(0);expect(saved()[0]).toMatchObject({id:original.id,created_at:original.created_at,done:1,deadline_raw:'旧截止'});await page.keyboard.press('Control+y');await caret('前文');await page.keyboard.press('ArrowLeft');await page.keyboard.press('Delete');await expect(editor().locator('.event-divider')).toHaveCount(0);await expect(editor().locator(':scope > ol').first()).toHaveClass(/done-content/);await page.keyboard.press('Control+z');await caret('前文');await page.keyboard.press('Backspace');await expect(editor().locator('.event-divider')).toHaveCount(0);await page.keyboard.press('Control+z');await page.keyboard.press('Control+a');await page.keyboard.press('ArrowLeft');await page.keyboard.press('Delete');await expect(editor().locator('.event-divider')).toHaveCount(0);await valid();await expect(editor()).toContainText('引用正文');
});
test('splitting a nested quote, typing and deleting its boundary each undo separately',async()=>{
  await caret('引用正文',2);await page.keyboard.press('Control+h');await valid();await page.keyboard.type('new');await expect(editor()).toContainText('new');await page.keyboard.press('Control+z');await expect(editor()).not.toContainText('new');await expect(editor().locator('.event-divider')).toHaveCount(1);await page.keyboard.press('Control+z');await expect(editor().locator('.event-divider')).toHaveCount(0);await page.keyboard.press('Control+y');await caret('引用',2);await page.keyboard.press('Delete');await expect(editor().locator('.event-divider')).toHaveCount(0);await page.keyboard.press('Control+z');await expect(editor().locator('.event-divider')).toHaveCount(1);await valid();
});
test('a cross-event cut from nested text restores both events after the cut was saved',async()=>{
  await caret('甲乙丙丁',2);await page.keyboard.press('Control+h');await expect.poll(()=>saved().length).toBe(2);const ids=saved().map(e=>e.id);
  await editor().evaluate((el:any)=>{let from=-1,to=-1;el.editor.state.doc.descendants((n:any,p:number)=>{if(n.isText&&n.text==='甲乙')from=p+1;if(n.isText&&n.text==='丙丁')to=p+1;});el.editor.commands.setTextSelection({from,to});});await page.keyboard.press('Control+x');await expect.poll(()=>saved().length).toBe(1);await valid();await expect(editor()).not.toContainText('乙');await expect(editor()).not.toContainText('丙');await page.keyboard.press('Control+z');await expect.poll(()=>saved().length).toBe(2);expect(saved().map(e=>e.id)).toEqual(ids);await expect(editor()).toContainText('甲乙');await expect(editor()).toContainText('丙丁');await valid();
});
