import {_electron,expect,test,type ElectronApplication,type Page} from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import Database from 'better-sqlite3';
import {DocumentStore} from '../../src/main/storage';
import browserImages from '../fixtures/browser-images.json';
import {imageFixtures} from '../fixtures/image-formats';
let app:ElectronApplication,page:Page,root:string,file:string;
const editor=()=>page.locator('.document-scroller:visible .todo-document');
const qtEnv=()=>({...process.env,QT_QPA_PLATFORM:'windows',PATH:'E:\\Qt\\6.8.3\\mingw_64\\bin;E:\\Qt\\Tools\\mingw1310_64\\bin;'+process.env.PATH});
function saved(){const db=new Database(file,{readonly:true});try{return {events:db.prepare('select * from events order by pos').all() as any[],assets:db.prepare('select * from assets order by id').all() as any[]};}finally{db.close();}}
async function copy(files:string[]){const input=path.join(root,'copy-files.json');await fs.writeFile(input,JSON.stringify({files}));return JSON.parse(execFileSync(path.resolve('.cache/qt-compat/qt-compat.exe'),['copy-files',input],{encoding:'utf8',windowsHide:true,env:qtEnv()}));}
async function rawClipboard(files:string[],wide=true,invalid=false){const header=Buffer.alloc(20);header.writeUInt32LE(invalid?0xffffff:20);header.writeUInt32LE(wide?1:0,16);const bytes=Buffer.from(files.join('\0')+'\0\0',wide?'utf16le':'latin1'),input=path.join(root,'transfer.bin');await fs.writeFile(input,Buffer.concat([header,bytes]));execFileSync(path.resolve('.cache/native/file-clipboard-test.exe'),[input],{windowsHide:true});}
test.beforeAll(()=>{const compiler='E:/Qt/Tools/mingw1310_64/bin/gcc.exe';execFileSync(compiler,['-std=c11','-O2','-s','-static','tests/fixtures/file-clipboard.c','-luser32','-o','.cache/native/file-clipboard-test.exe'],{windowsHide:true,env:{...process.env,PATH:path.dirname(compiler)+';'+process.env.PATH}});});
async function pictures(){const files=[];for(const [name,w,h,c] of [['中文 橙色 😀.png',200,100,230],['blue.PNG',120,300,70]] as const){const data=Buffer.from(await app.evaluate(({nativeImage},{w,h,c})=>{const pixels=Buffer.alloc(w*h*4);for(let i=0;i<pixels.length;i+=4){pixels[i]=255-c;pixels[i+1]=120;pixels[i+2]=c;pixels[i+3]=255;}return Array.from(nativeImage.createFromBitmap(pixels,{width:w,height:h}).toPNG());},{w,h,c}));const file=path.join(root,name);await fs.writeFile(file,data);files.push({file,data,w,h});}return files;}
test.beforeEach(async({},info)=>{root=info.outputPath('workspace');await fs.mkdir(root,{recursive:true});file=path.join(root,'文件剪贴板.tde');const store=new DocumentStore(),doc=store.open(file,true);await store.save({...doc,events:[{id:-1,pos:0,created_at:1750000000,deadline_raw:'',deadline_ts:null,done:0,top_divider:0,content_html:'<p>abcdef</p>',content_text:'abcdef'}]});store.close(doc.handle);const env:NodeJS.ProcessEnv={...process.env,TODOLINE_TEST:'1',TODOLINE_DATA_DIR:path.join(root,'profile')};delete env.ELECTRON_RUN_AS_NODE;app=await _electron.launch({args:[path.resolve('.'),'--open',file],env:env as Record<string,string>});page=await app.firstWindow();await app.evaluate(({BrowserWindow})=>{BrowserWindow.getAllWindows()[0].show();BrowserWindow.getAllWindows()[0].focus();});await expect(editor()).toBeVisible();await editor().evaluate((el:any)=>{el.editor.commands.setTextSelection(3);el.editor.view.focus();});});
test.afterEach(async({},info)=>{if(info.status!==info.expectedStatus)await page?.screenshot({path:info.outputPath('failure.png')}).catch(()=>{});await app?.evaluate(({app})=>app.exit(0)).catch(()=>{});});
test('real Windows file clipboard inserts ordered original images and undoes the complete batch',async({},info)=>{const images=await pictures();await copy(images.map(i=>i.file));expect(await app.evaluate(({clipboard})=>clipboard.availableFormats())).toContain('text/uri-list');await page.keyboard.press('Control+v');await expect(editor().locator('.image-view')).toHaveCount(2);await expect(editor()).toHaveText('abcdef');await expect.poll(()=>saved().events[0].content_html.match(/asset:/g)?.length).toBe(2);saved().assets.forEach((a,i)=>{expect(Buffer.from(a.data)).toEqual(images[i].data);expect([a.w,a.h]).toEqual([images[i].w,images[i].h]);});await expect(editor().locator('.image-view img').first()).toHaveCSS('width','200px');await page.screenshot({path:info.outputPath('file-images.png')});await page.keyboard.press('Control+z');await expect(editor().locator('.image-view')).toHaveCount(0);await expect(editor()).toHaveText('abcdef');await page.keyboard.press('Control+y');await expect(editor().locator('.image-view')).toHaveCount(2);expect(await fs.readFile(images[0].file)).toEqual(images[0].data);});
test('a corrupt later image preserves selected text and leaves no assets before retry',async()=>{const images=await pictures(),bad=path.join(root,'损坏.png');await fs.writeFile(bad,'not an image');await page.keyboard.press('Control+a');await copy([images[0].file,bad]);await page.keyboard.press('Control+v');await expect(page.locator('.toast')).toContainText('损坏.png');await expect(editor()).toHaveText('abcdef');expect(saved().assets).toHaveLength(0);await page.getByRole('button',{name:'关闭消息'}).click();await editor().focus();await copy(images.map(i=>i.file));await page.keyboard.press('Control+v');await expect(editor().locator('.image-view')).toHaveCount(2);await expect(editor()).toHaveText('');await page.keyboard.press('Control+z');await expect(editor()).toHaveText('abcdef');});
test('a deleted source aborts the batch without touching the current document',async()=>{const images=await pictures();await copy(images.map(i=>i.file));await fs.unlink(images[1].file);await page.keyboard.press('Control+v');await expect(page.locator('.toast')).toContainText('blue.PNG');expect(saved().assets).toHaveLength(0);await expect(editor()).toHaveText('abcdef');});
test('mixed file selections paste their URL text without partially importing images',async()=>{const images=await pictures(),text=path.join(root,'中文文档.txt');await fs.writeFile(text,'private file contents');const copied=await copy([images[0].file,text]);await page.keyboard.press('Control+v');await expect(editor()).toContainText('file:///');await expect(editor().locator('.image-view')).toHaveCount(0);expect(saved().assets).toHaveLength(0);expect(await editor().innerText()).not.toContain('private file contents');await expect.poll(()=>saved().events[0].content_text).toContain('file:///');const actual=saved().events[0].content_text;expect(decodeURI(actual).replace(/\n+cdef$/,'cdef')).toBe(('ab'+copied.text+'cdef').replace(/\n+cdef$/,'cdef'));});
test('pasting file images from a line highlight keeps the highlighted text',async()=>{const images=await pictures();await page.locator('.document-scroller:visible .line-label').first().click();await expect(editor().locator('.row-selection')).toHaveCount(1);await copy(images.map(i=>i.file));await page.keyboard.press('Control+v');await expect(editor().locator('.image-view')).toHaveCount(2);await expect(editor()).toHaveText('abcdef');await expect(editor().locator('.row-selection')).toHaveCount(0);await page.keyboard.press('Control+z');await expect(editor()).toHaveText('abcdef');});
test('Qt can edit the resulting file and original image bytes survive reopening',async()=>{const images=await pictures();await copy(images.map(i=>i.file));await page.keyboard.press('Control+v');await expect(editor().locator('.image-view')).toHaveCount(2);await expect.poll(()=>saved().events[0].content_html.match(/asset:/g)?.length).toBe(2);await page.locator('.file-tab.active .tab-close').click();await expect(page.locator('.file-tab')).toHaveCount(0);execFileSync(path.resolve('.cache/qt-compat/qt-compat.exe'),['edit',file],{windowsHide:true,env:{...qtEnv(),QT_QPA_PLATFORM:'offscreen'}});await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},file);await page.getByRole('button',{name:'打开文档 · Ctrl+O',exact:true}).click();await expect(editor()).toContainText('旧版再次编辑');await expect(editor().locator('.image-view')).toHaveCount(2);saved().assets.forEach((a,i)=>expect(Buffer.from(a.data)).toEqual(images[i].data));});
test('standard CF_HDROP without Qt formats supports UTF-16 and legacy ANSI file lists',async()=>{const images=await pictures();for(const wide of [true,false]){const chosen=wide?images:images.slice(1);await rawClipboard(chosen.map(i=>i.file),wide);expect(await app.evaluate(({clipboard})=>clipboard.availableFormats())).toContain('text/uri-list');await page.keyboard.press('Control+v');await expect(editor().locator('.image-view')).toHaveCount(chosen.length);await expect.poll(()=>saved().events[0].content_html.match(/asset:/g)?.length).toBe(chosen.length);await page.keyboard.press('Control+z');await expect(editor().locator('.image-view')).toHaveCount(0);}});
test('malformed native file offsets do not read files or delete selected content',async()=>{const images=await pictures();await page.keyboard.press('Control+a');await rawClipboard(images.map(i=>i.file),true,true);await page.keyboard.press('Control+v');await expect(page.locator('.toast')).toContainText('无法读取文件剪贴板');await expect(editor()).toHaveText('abcdef');expect(saved().assets).toHaveLength(0);await page.getByRole('button',{name:'关闭消息'}).click();await editor().focus();await rawClipboard(images.map(i=>i.file));await page.keyboard.press('Control+v');await expect(editor().locator('.image-view')).toHaveCount(2);await expect(editor()).toHaveText('');});
test('file clipboard preserves animated GIF, WebP and TIFF original encodings',async({},info)=>{const fixtures=[...browserImages.filter(i=>i.name.startsWith('animated.')).map(i=>({...i,buffer:Buffer.from(i.data,'base64')})),imageFixtures[0]],files=[];for(const fixture of fixtures){const name=path.join(root,fixture.name);await fs.writeFile(name,fixture.buffer);files.push(name);}await rawClipboard(files);await page.keyboard.press('Control+v');await expect(editor().locator('.image-view')).toHaveCount(fixtures.length);await editor().locator('.image-view img').evaluateAll(async images=>Promise.all(images.map(image=>(image as HTMLImageElement).decode())));await expect.poll(()=>saved().events[0].content_html.match(/asset:/g)?.length).toBe(fixtures.length);saved().assets.forEach((a,i)=>expect(Buffer.from(a.data)).toEqual(fixtures[i].buffer));await page.screenshot({path:info.outputPath('original-formats.png')});await page.keyboard.press('Control+z');await expect(editor().locator('.image-view')).toHaveCount(0);});
