import {_electron,expect,test,type ElectronApplication,type Page} from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import Database from 'better-sqlite3';
import {execFileSync} from 'node:child_process';
import {DocumentStore} from '../../src/main/storage';
let app:ElectronApplication,page:Page,root:string,file:string,other:string;
const editor=()=>page.locator('.document-scroller:visible .todo-document');
const input=()=>page.locator('input[type=file]');
function saved(target=file){const db=new Database(target,{readonly:true});try{return {events:db.prepare('select * from events order by pos').all() as any[],assets:db.prepare('select * from assets order by id').all() as any[]};}finally{db.close();}}
async function pictures(){return Promise.all([{name:'橙色.png',w:200,h:100,c:220},{name:'蓝色.png',w:120,h:300,c:80}].map(async a=>({name:a.name,mimeType:'image/png',buffer:Buffer.from(await app.evaluate(({nativeImage},a)=>{const pixels=Buffer.alloc(a.w*a.h*4);for(let i=0;i<pixels.length;i+=4){pixels[i]=255-a.c;pixels[i+1]=120;pixels[i+2]=a.c;pixels[i+3]=255;}return Array.from(nativeImage.createFromBitmap(pixels,{width:a.w,height:a.h}).toPNG());},a))})));}
async function caret(pos=3){await editor().evaluate((el:any,pos)=>{el.editor.commands.setTextSelection(pos);el.editor.view.focus();},pos);}
async function delayFirst(){await page.evaluate(()=>{const original=File.prototype.arrayBuffer;File.prototype.arrayBuffer=async function(){if(this.name==='橙色.png'){(window as any).imageReadStarted=true;await new Promise<void>(resolve=>{(window as any).releaseImageRead=resolve;});}return original.call(this);};});}
async function release(){await expect.poll(()=>page.evaluate(()=>(window as any).imageReadStarted)).toBe(true);await page.evaluate(()=>(window as any).releaseImageRead());}
test.beforeEach(async({},info)=>{
  root=info.outputPath('workspace');await fs.mkdir(root,{recursive:true});file=path.join(root,'图片来源.tde');other=path.join(root,'其他文档.tde');const store=new DocumentStore();for(const target of [file,other]){const doc=store.open(target,true);await store.save({...doc,events:[{id:-1,pos:0,created_at:1750000000,deadline_raw:'',deadline_ts:null,done:0,top_divider:0,content_html:'<p>abcdef</p>',content_text:'abcdef'}]});store.close(doc.handle);}
  const env:NodeJS.ProcessEnv={...process.env,TODOLINE_TEST:'1',TODOLINE_DATA_DIR:path.join(root,'profile')};delete env.ELECTRON_RUN_AS_NODE;app=await _electron.launch({args:[path.resolve('.'),'--open',file],env:env as Record<string,string>});page=await app.firstWindow();await app.evaluate(({BrowserWindow})=>{BrowserWindow.getAllWindows()[0].show();BrowserWindow.getAllWindows()[0].focus();});await expect(editor()).toBeVisible();
});
test.afterEach(async({},info)=>{if(info.status!==info.expectedStatus)await page?.screenshot({path:info.outputPath('failure.png')}).catch(()=>{});await app?.evaluate(({app})=>app.exit(0)).catch(()=>{});});
test('file picker inserts every original image in order and the whole batch undoes once after saving',async({},info)=>{
  const files=await pictures();await caret();await input().setInputFiles(files);await expect(editor().locator('.image-view')).toHaveCount(2);await expect.poll(()=>saved().events[0].content_html).toMatch(/asset:\d+[\s\S]*asset:\d+/);const state=saved();expect(state.assets.map(a=>[a.w,a.h])).toEqual([[200,100],[120,300]]);state.assets.forEach((a,i)=>expect(Buffer.from(a.data)).toEqual(files[i].buffer));await page.screenshot({path:info.outputPath('multi-image.png')});await page.keyboard.press('Control+z');await expect(editor().locator('.image-view')).toHaveCount(0);await expect.poll(()=>saved().events[0].content_html).not.toContain('asset:');await page.keyboard.press('Control+y');await expect(editor().locator('.image-view')).toHaveCount(2);
});
test('a multi-file drop with missing MIME types keeps its source document and display sizes after switching tabs',async()=>{
  const files=await pictures();await delayFirst();const box=await editor().locator('p').boundingBox();const dt=await page.evaluateHandle(files=>{const data=new DataTransfer();for(const f of files)data.items.add(new File([new Uint8Array(f.data)],f.name));return data;},files.map(f=>({name:f.name,data:Array.from(f.buffer)})));await editor().dispatchEvent('drop',{dataTransfer:dt,clientX:box!.x+15,clientY:box!.y+8});await expect(page.locator('.statusbar')).toContainText('正在导入 2 张图片');
  await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},other);await page.getByRole('button',{name:'打开文档 · Ctrl+O',exact:true}).click();await expect(page.locator('.file-tab.active')).toContainText('其他文档');await release();await expect.poll(()=>saved().assets.length).toBe(2);await expect.poll(()=>saved().events[0].content_html).toContain('width="200"');expect(saved(other).assets).toHaveLength(0);await expect(editor().locator('.image-view')).toHaveCount(0);await page.locator('.tab-name').first().click();await expect(editor().locator('.image-view')).toHaveCount(2);await expect(editor().locator('.image-view img').nth(1)).toHaveCSS('width','120px');
});
test('separate pending imports retain invocation order and have separate undo steps',async()=>{
  const files=await pictures();await delayFirst();await caret();await input().setInputFiles(files[0]);await input().setInputFiles(files[1]);await expect(page.locator('.statusbar')).toContainText('正在导入 2 张图片');await release();await expect(editor().locator('.image-view')).toHaveCount(2);await expect(editor().locator('.image-view img').first()).toHaveCSS('width','200px');await page.keyboard.press('Control+z');await expect(editor().locator('.image-view')).toHaveCount(1);await expect(editor().locator('.image-view img')).toHaveCSS('width','200px');await page.keyboard.press('Control+z');await expect(editor().locator('.image-view')).toHaveCount(0);
});
test('native paste after a slow file import preserves invocation order, saved bytes and separate undo',async()=>{
  const files=await pictures();await delayFirst();await caret();await input().setInputFiles(files[0]);await expect.poll(()=>page.evaluate(()=>(window as any).imageReadStarted)).toBe(true);
  await app.evaluate(({clipboard})=>{clipboard.clear();clipboard.writeText('后粘贴');});await editor().focus();await page.keyboard.press('Control+v');await release();await expect(editor().locator('.image-view')).toHaveCount(1);await expect(editor()).toHaveText('ab后粘贴cdef');
  expect(await editor().evaluate((el:any)=>el.editor.state.doc.firstChild.content.content.map((n:any)=>n.isText?n.text:n.type.name))).toEqual(['ab','image','后粘贴cdef']);await expect.poll(()=>saved().events[0].content_html).toMatch(/asset:\d+[\s\S]*后粘贴/);expect(Buffer.from(saved().assets[0].data)).toEqual(files[0].buffer);
  await page.keyboard.press('Control+z');await expect(editor()).toHaveText('abcdef');await expect(editor().locator('.image-view')).toHaveCount(1);await page.keyboard.press('Control+z');await expect(editor().locator('.image-view')).toHaveCount(0);await expect.poll(()=>saved().events[0].content_html).not.toContain('asset:');
});
test('file import after a slow all-selection paste appends and tab close saves both operations',async()=>{
  const files=await pictures();await app.evaluate(({ipcMain})=>{ipcMain.removeHandler('tl:readClipboard');ipcMain.handle('tl:readClipboard',async()=>{(globalThis as any).readStarted=true;await new Promise<void>(resolve=>{(globalThis as any).releaseRead=resolve;});return {text:'先粘贴',html:'',events:''};});});
  await caret();await page.keyboard.press('Control+a');await page.keyboard.press('Control+v');await expect.poll(()=>app.evaluate(()=>(globalThis as any).readStarted)).toBe(true);await input().setInputFiles(files[0]);await page.locator('.file-tab.active .tab-close').click();await expect(page.locator('.file-tab')).toHaveCount(1);await app.evaluate(()=>(globalThis as any).releaseRead());await expect(page.locator('.file-tab')).toHaveCount(0);
  const state=saved();expect(state.events[0].content_html).toMatch(/先粘贴[\s\S]*asset:\d+/);expect(state.events[0].content_text).not.toContain('abcdef');expect(Buffer.from(state.assets[0].data)).toEqual(files[0].buffer);
});
test('native cut at the edge of a pending image removes only copied text and keeps original pixels',async()=>{
  const files=await pictures();await delayFirst();await caret(4);await input().setInputFiles(files[0]);await expect.poll(()=>page.evaluate(()=>(window as any).imageReadStarted)).toBe(true);await caret(2);await page.keyboard.press('Shift+ArrowRight');await page.keyboard.press('Shift+ArrowRight');await page.keyboard.press('Control+x');await release();await expect(editor()).toHaveText('adef');await expect(editor().locator('.image-view')).toHaveCount(1);
  expect(await app.evaluate(({clipboard})=>clipboard.readText())).toBe('bc');await expect.poll(()=>saved().events[0].content_html).toMatch(/a<img[\s\S]*asset:\d+[\s\S]*def/);expect(Buffer.from(saved().assets[0].data)).toEqual(files[0].buffer);await page.keyboard.press('Control+z');await expect(editor()).toHaveText('abcdef');await expect(editor().locator('.image-view')).toHaveCount(1);
});
test('line-number cut keeps new edge images and a later caret when deletion would exceed copied content',async()=>{
  const files=await pictures();await delayFirst();await caret(7);await input().setInputFiles(files[0]);await expect.poll(()=>page.evaluate(()=>(window as any).imageReadStarted)).toBe(true);await page.locator('.document-scroller:visible .line-label').first().click();await expect(editor().locator('.row-selection')).toHaveCount(1);await page.keyboard.press('Control+x');await page.keyboard.press('Escape');await caret(4);await release();
  await expect(page.locator('.toast')).toContainText('等待期间目标内容已被修改');await expect(editor()).toHaveText('abcdef');await expect(editor().locator('.image-view')).toHaveCount(1);await expect(editor().locator('.row-selection')).toHaveCount(0);expect(await editor().evaluate((el:any)=>el.editor.state.selection.from)).toBe(4);expect(await app.evaluate(({clipboard})=>clipboard.readText())).toBe('abcdef');await expect.poll(()=>saved().events[0].content_html).toContain('asset:');
});
test('a bad file aborts the batch before storage and retry succeeds without partial content',async()=>{
  const files=await pictures();await caret();await input().setInputFiles([files[0],{name:'坏图.png',mimeType:'image/png',buffer:Buffer.from('not an image')}]);await expect(page.locator('.toast')).toContainText('坏图.png');await expect(editor().locator('.image-view')).toHaveCount(0);expect(saved().assets).toHaveLength(0);await expect(editor()).toHaveText('abcdef');await input().setInputFiles(files);await expect(editor().locator('.image-view')).toHaveCount(2);await expect.poll(()=>saved().assets.length).toBe(2);
});
test('closing a tab waits for the entire batch and saves both asset references',async()=>{
  const files=await pictures();await delayFirst();await caret();await input().setInputFiles(files);await expect(page.locator('.statusbar')).toContainText('正在导入 2 张图片');await page.locator('.file-tab.active .tab-close').click();await expect(page.locator('.file-tab')).toHaveCount(1);await release();await expect(page.locator('.file-tab')).toHaveCount(0);const state=saved();expect(state.assets).toHaveLength(2);for(const a of state.assets)expect(state.events[0].content_html).toContain('asset:'+a.id);
});
test('the main process rejects a malformed member without inserting any of the batch',async()=>{
  const files=await pictures();const message=await page.evaluate(async data=>{const doc=await window.desktop.openRecent((await window.desktop.session()).tabs[0].path);try{await window.desktop.addAssets(doc.handle,[{data:new Uint8Array(data),w:1,h:1},{data:new Uint8Array([1,2,3]),w:1,h:1}]);return '';}catch(e){return String(e);}},Array.from(files[0].buffer));expect(message).toContain('无法读取图片');expect(saved().assets).toHaveLength(0);
});
test('Qt edits a newly imported batch and both original PNGs and display sizes survive reopening',async()=>{
  const files=await pictures();await caret();await input().setInputFiles(files);await expect(editor().locator('.image-view')).toHaveCount(2);await expect.poll(()=>saved().events[0].content_html).toContain('asset:');await page.locator('.file-tab.active .tab-close').click();await expect(page.locator('.file-tab')).toHaveCount(0);
  execFileSync(path.resolve('.cache/qt-compat/qt-compat.exe'),['edit',file],{windowsHide:true,env:{...process.env,QT_QPA_PLATFORM:'offscreen',PATH:'E:\\Qt\\6.8.3\\mingw_64\\bin;E:\\Qt\\Tools\\mingw1310_64\\bin;'+process.env.PATH}});
  await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},file);await page.getByRole('button',{name:'打开文档 · Ctrl+O',exact:true}).click();await expect(editor()).toContainText('旧版再次编辑');await expect(editor().locator('.image-view')).toHaveCount(2);await expect(editor().locator('.image-view img').first()).toHaveCSS('width','200px');await expect(editor().locator('.image-view img').last()).toHaveCSS('height','300px');saved().assets.forEach((a,i)=>expect(Buffer.from(a.data)).toEqual(files[i].buffer));
});
