import {_electron,expect,test,type ElectronApplication,type Page} from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import Database from 'better-sqlite3';
import {DocumentStore} from '../../src/main/storage';
import {clipboardPacket} from '../../src/main/clipboard-format';
import type {EventRecord} from '../../src/shared/types';
let app:ElectronApplication,page:Page,root:string,file:string;
const opaque='<table style="float:left"><tr><td>原格式</td></tr></table>';
const record=(html='<p>abcdef</p>',text='abcdef'):EventRecord=>({id:-1,pos:0,created_at:1750000000,deadline_raw:'明天',deadline_ts:1750089600,done:1,top_divider:0,content_html:html,content_text:text});
const editor=()=>page.locator('.document-scroller:visible .todo-document');
function saved(){const db=new Database(file,{readonly:true});try{return {events:db.prepare('select * from events order by pos').all() as EventRecord[],assets:db.prepare('select * from assets order by id').all() as any[]};}finally{db.close();}}
function clipboard(html=opaque,assets:unknown[]=[],top_divider=true){const events=[{created_at:123,html,text:'原格式',top_divider}];execFileSync(path.resolve('out/main/clipboard-win.exe'),{input:clipboardPacket([{name:'CF_UNICODETEXT',data:Buffer.from('\0','utf16le')},{name:'application/x-tde-events',data:Buffer.from(JSON.stringify({events,assets}))}]),windowsHide:true});}
async function start(events=[record()]){const store=new DocumentStore(),doc=store.open(file,true);await store.save({...doc,events:events.map((e,i)=>({...e,id:-(i+1),pos:i*1024}))});store.close(doc.handle);const env:NodeJS.ProcessEnv={...process.env,TODOLINE_TEST:'1',TODOLINE_DATA_DIR:path.join(root,'profile')};delete env.ELECTRON_RUN_AS_NODE;app=await _electron.launch({args:[path.resolve('.'),'--open',file],env:env as Record<string,string>});page=await app.firstWindow();await app.evaluate(({BrowserWindow})=>{BrowserWindow.getAllWindows()[0].show();BrowserWindow.getAllWindows()[0].focus();});await expect(editor()).toBeVisible();await editor().focus();}
async function reopen(qt=false){await page.locator('.file-tab.active .tab-close').click();await expect(page.locator('.file-tab')).toHaveCount(0);if(qt)execFileSync(path.resolve('.cache/qt-compat/qt-compat.exe'),['edit',file],{windowsHide:true,env:{...process.env,QT_QPA_PLATFORM:'offscreen',PATH:'E:/Qt/6.8.3/mingw_64/bin;E:/Qt/Tools/mingw1310_64/bin;'+process.env.PATH}});await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},file);await page.getByRole('button',{name:'打开文档 · Ctrl+O',exact:true}).click();await expect(editor()).toBeVisible();}
test.beforeEach(async({},info)=>{root=info.outputPath('workspace');file=path.join(root,'只读事件.tde');await fs.mkdir(root,{recursive:true});});
test.afterEach(async({},info)=>{if(info.status!==info.expectedStatus)await page?.screenshot({path:info.outputPath('failure.png')}).catch(()=>{});await app?.evaluate(({app})=>app.exit(0)).catch(()=>{});});
test('opaque event paste keeps surrounding saved text, original image bytes and history through a Qt round trip',async({},info)=>{
  await start();const bytes=Buffer.from(await app.evaluate(({nativeImage})=>{const pixels=Buffer.alloc(32*24*4,255);return Array.from(nativeImage.createFromBitmap(pixels,{width:32,height:24}).toPNG());})),html=opaque.replace('原格式','原格式<img src="asset:1" width="16" height="12" />');
  await editor().evaluate((el:any)=>{el.editor.commands.setTextSelection(3);el.editor.view.focus();});clipboard(html,[{name:'asset:1',data:bytes.toString('base64')}]);await page.keyboard.press('Control+v');await expect(editor().locator('.legacy-content')).toHaveCount(1);await expect.poll(()=>saved().events.map(e=>e.content_text)).toEqual(['ab','原格式','cdef']);expect(saved().events[1].content_html).toBe(html);expect(Buffer.from(saved().assets[0].data)).toEqual(bytes);expect(saved().events[2]).toMatchObject({created_at:1750000000,deadline_raw:'明天',deadline_ts:1750089600,done:1});
  await page.keyboard.press('Control+z');await expect.poll(()=>saved().events.map(e=>e.content_text)).toEqual(['abcdef']);await page.keyboard.press('Control+y');await expect.poll(()=>saved().events.map(e=>e.content_text)).toEqual(['ab','原格式','cdef']);await page.screenshot({path:info.outputPath('opaque-surroundings.png')});
  await reopen();await expect(editor().locator('.legacy-content')).toHaveCount(1);expect(saved().events[1].content_html).toBe(html);await reopen(true);await expect(editor()).toContainText('旧版再次编辑');const rows=saved().events;expect(rows).toHaveLength(3);expect(rows[0].content_text).toContain('ab');expect(rows[1].content_text).toContain('原格式');expect(rows[2].content_text).toContain('cdef');expect(Buffer.from(saved().assets[0].data)).toEqual(bytes);
});
test('adding a second opaque event and undoing it preserves the first raw event after saving',async()=>{
  await start([{...record(opaque,'原格式'),top_divider:1},record()]);await editor().evaluate((el:any)=>{el.editor.commands.setTextSelection(el.editor.state.doc.content.size-1);el.editor.view.focus();});clipboard();await page.keyboard.press('Control+v');await expect(editor().locator('.legacy-content')).toHaveCount(2);await expect.poll(()=>saved().events.filter(e=>e.content_html===opaque).length).toBe(2);await page.keyboard.press('Control+z');await expect.poll(()=>saved().events.map(e=>e.content_text)).toEqual(['原格式','abcdef']);await page.keyboard.press('Control+y');await expect.poll(()=>saved().events.filter(e=>e.content_html===opaque).length).toBe(2);
});
test('replacing existing opaque content is rejected before assets are decoded or written',async()=>{
  await start([record(opaque,'原格式')]);await page.keyboard.press('Control+a');clipboard('<p><img src="asset:1" /></p>',[{name:'asset:1',data:'AQI='}]);await page.keyboard.press('Control+v');await expect(page.locator('.toast')).toContainText('只读');expect(saved().assets).toHaveLength(0);expect(saved().events[0].content_html).toBe(opaque);
});
test('a dividerless opaque full-document paste preserves metadata across save undo redo and reopen',async()=>{
  await start();await page.keyboard.press('Control+a');clipboard(opaque,[],false);await page.keyboard.press('Control+v');await expect.poll(()=>saved().events[0].content_html).toBe(opaque);expect(saved().events).toHaveLength(1);expect(saved().events[0]).toMatchObject({created_at:123,top_divider:0});await editor().focus();await page.keyboard.press('Control+z');await expect.poll(()=>saved().events[0].content_text).toBe('abcdef');await page.keyboard.press('Control+y');await expect.poll(()=>saved().events[0].content_html).toBe(opaque);await reopen();await expect(editor().locator('.legacy-content')).toHaveCount(1);expect(saved().events[0]).toMatchObject({created_at:123,top_divider:0});
});
test('Ctrl+A and Ctrl+C copies a wholly opaque document into another file with its raw format',async()=>{
  await start([record(opaque,'原格式')]);await app.evaluate(({clipboard})=>clipboard.clear());await page.keyboard.press('Control+a');await page.keyboard.press('Control+c');await expect.poll(()=>app.evaluate(({clipboard})=>clipboard.readBuffer('application/x-tde-events').toString())).toContain('float:left');await expect(page.locator('.toast'),'copy must not mutate the source').toHaveCount(0);await page.getByRole('button',{name:'新建文档 · Ctrl+N',exact:true}).click();await expect(page.locator('.file-tab.active')).toContainText(/\d{8}_\d+/);await expect(editor().locator('.legacy-content')).toHaveCount(0);await editor().focus();await page.keyboard.press('Control+v');await expect(editor().locator('.legacy-content')).toHaveCount(1);await expect(page.locator('.toast')).toHaveCount(0);await page.keyboard.press('Control+z');await expect(editor().locator('.legacy-content')).toHaveCount(0);
});
