import {_electron,expect,test,type ElectronApplication,type Page} from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import Database from 'better-sqlite3';
import {DocumentStore} from '../../src/main/storage';
let app:ElectronApplication,page:Page,root:string,file:string;
const editor=()=>page.locator('.document-scroller:visible .todo-document');
function saved(){const db=new Database(file,{readonly:true});try{return {events:db.prepare('select * from events order by pos').all() as any[],assets:db.prepare('select * from assets order by id').all() as any[]};}finally{db.close();}}
async function columns(){const rect=await editor().evaluate((el:any)=>{el.style.fontFamily='Consolas';const a=el.editor.view.coordsAtPos(2),b=el.editor.view.coordsAtPos(20);return {x:a.left+.2,y:(a.top+a.bottom)/2,right:b.left+.2,bottom:(b.top+b.bottom)/2};});await page.keyboard.down('Alt');await page.mouse.move(rect.x,rect.y);await page.mouse.down();await page.mouse.move(rect.right,rect.bottom,{steps:6});await page.mouse.up();await page.keyboard.up('Alt');await expect(editor().locator('.column-selection')).toHaveCount(3);}
async function rows(indices=[0,2]){for(const [i,index]of indices.entries())await page.locator('.document-scroller:visible .line-label').nth(index).click({modifiers:i?['Control']:[]});await expect(editor().locator('.row-selection')).toHaveCount(indices.length);}
test.beforeEach(async({},info)=>{root=info.outputPath('workspace');await fs.mkdir(root,{recursive:true});file=path.join(root,'列编辑.tde');const store=new DocumentStore(),doc=store.open(file,true);await store.save({...doc,events:[{id:-1,pos:0,created_at:1750000000,deadline_raw:'',deadline_ts:null,done:0,top_divider:0,content_html:'<p>abcdef</p><p>ghijkl</p><p>mnopqr</p>',content_text:'abcdef\nghijkl\nmnopqr'}]});store.close(doc.handle);const env:NodeJS.ProcessEnv={...process.env,TODOLINE_TEST:'1',TODOLINE_DATA_DIR:path.join(root,'profile')};delete env.ELECTRON_RUN_AS_NODE;app=await _electron.launch({args:[path.resolve('.'),'--open',file],env:env as Record<string,string>});page=await app.firstWindow();await app.evaluate(({BrowserWindow})=>{BrowserWindow.getAllWindows()[0].show();BrowserWindow.getAllWindows()[0].focus();});await expect(editor()).toBeVisible();});
test.afterEach(async({},info)=>{if(info.status!==info.expectedStatus)await page?.screenshot({path:info.outputPath('failure.png')}).catch(()=>{});await app?.evaluate(({app})=>app.exit(0)).catch(()=>{});});
for(const mode of ['column','row']){
  test(`empty clipboard preserves ${mode} text and selection`,async()=>{await(mode==='column'?columns():rows());await app.evaluate(({clipboard})=>clipboard.clear());await page.keyboard.press('Control+v');await expect(editor().locator('p')).toHaveText(['abcdef','ghijkl','mnopqr']);await expect(editor().locator(mode==='column'?'.column-selection':'.row-selection')).toHaveCount(mode==='column'?3:2);expect(saved().events[0].content_text).toBe('abcdef\nghijkl\nmnopqr');});
  test(`native image exits ${mode} mode, inserts once at the primary caret and saves original pixels`,async()=>{
    await(mode==='column'?columns():rows());const pos=await editor().evaluate((el:any)=>el.editor.state.selection.from),png=await app.evaluate(({clipboard,nativeImage})=>{const image=nativeImage.createFromBitmap(Buffer.alloc(32*24*4,255),{width:32,height:24});clipboard.clear();clipboard.writeImage(image);return Array.from(clipboard.readImage().toPNG());});await page.keyboard.press('Control+v');await expect(editor().locator('.image-view')).toHaveCount(1);await expect(editor().locator('.column-selection,.row-selection,.column-caret')).toHaveCount(0);await expect(editor().locator('p')).toHaveText(['abcdef','ghijkl','mnopqr']);expect(await editor().evaluate((el:any)=>{let pos=-1;el.editor.state.doc.descendants((n:any,p:number)=>{if(n.type.name==='image')pos=p;});return pos;})).toBe(pos);await expect.poll(()=>saved().events[0].content_html).toContain('asset:');expect(Buffer.from(saved().assets[0].data)).toEqual(Buffer.from(png));await page.keyboard.press('Control+z');await expect(editor().locator('.image-view')).toHaveCount(0);await expect.poll(()=>saved().events[0].content_text).toBe('abcdef\nghijkl\nmnopqr');
  });
}
test('native typing retains three visible carets, deletion and undo operate on every row',async({},info)=>{
  await columns();await page.keyboard.type('XY');await expect(editor().locator('p')).toHaveText(['aXYdef','gXYjkl','mXYpqr']);await expect(editor().locator('.column-caret')).toHaveCount(3);await page.screenshot({path:info.outputPath('column-carets.png')});await page.keyboard.press('Backspace');await expect(editor().locator('p')).toHaveText(['aXdef','gXjkl','mXpqr']);await page.keyboard.press('Delete');await expect(editor().locator('p')).toHaveText(['aXef','gXkl','mXqr']);await expect.poll(()=>saved().events[0].content_text).toBe('aXef\ngXkl\nmXqr');await page.keyboard.press('Control+z');await expect(editor().locator('p')).toHaveText(['aXdef','gXjkl','mXpqr']);await expect(editor().locator('.column-caret')).toHaveCount(0);await page.keyboard.press('Control+z');await expect(editor().locator('p')).toHaveText(['aXYdef','gXYjkl','mXYpqr']);
});
test('multiline clipboard exits columns and inserts only once without deleting the rectangle',async()=>{
  await columns();await app.evaluate(({clipboard})=>{clipboard.clear();clipboard.writeText('X\nY');});await page.keyboard.press('Control+v');await expect(editor().locator('p')).toHaveText(['aX','Ybcdef','ghijkl','mnopqr']);await expect(editor().locator('.column-selection,.column-caret')).toHaveCount(0);await expect.poll(()=>saved().events[0].content_text).toBe('aX\nYbcdef\nghijkl\nmnopqr');
});
test('two queued native column pastes append at all carets in order',async()=>{
  await columns();await app.evaluate(({ipcMain})=>{let count=0;ipcMain.removeHandler('tl:readClipboard');ipcMain.handle('tl:readClipboard',async()=>{if(count++===0){(globalThis as any).started=true;await new Promise<void>(resolve=>{(globalThis as any).release=resolve;});return {text:'X',events:'',html:''};}return {text:'Y',events:'',html:''};});});await page.keyboard.press('Control+v');await expect.poll(()=>app.evaluate(()=>(globalThis as any).started)).toBe(true);await page.keyboard.press('Control+v');await app.evaluate(()=>(globalThis as any).release());await expect(editor().locator('p')).toHaveText(['aXYdef','gXYjkl','mXYpqr']);await expect(editor().locator('.column-caret')).toHaveCount(3);await expect.poll(()=>saved().events[0].content_text).toBe('aXYdef\ngXYjkl\nmXYpqr');
});
test('row paste retains an intentionally empty line and undoes after saving',async()=>{
  await rows([0,1]);await app.evaluate(({clipboard})=>{clipboard.clear();clipboard.writeText('X\n');});await page.keyboard.press('Control+v');await expect(editor().locator('p')).toHaveText(['X','','mnopqr']);await expect.poll(()=>saved().events[0].content_text).toBe('X\n\nmnopqr');await page.keyboard.press('Control+z');await expect(editor().locator('p')).toHaveText(['abcdef','ghijkl','mnopqr']);
});
test('Chinese composition exits columns and keeps the editor DOM and other rows intact',async()=>{
  await columns();const dom=await editor().elementHandle(),cdp=await page.context().newCDPSession(page);await cdp.send('Input.imeSetComposition',{text:'zhong',selectionStart:5,selectionEnd:5});await expect(editor().locator('.column-selection,.column-caret')).toHaveCount(0);await cdp.send('Input.insertText',{text:'中文'});await expect(editor().locator('p')).toHaveText(['a中文bcdef','ghijkl','mnopqr']);expect(await dom!.evaluate(el=>el.isConnected)).toBe(true);await expect.poll(()=>saved().events[0].content_text).toBe('a中文bcdef\nghijkl\nmnopqr');
});
test('file-picker batch exits column mode only after decoding succeeds and undoes once',async()=>{
  await columns();await page.locator('input[type=file]').setInputFiles({name:'损坏.png',mimeType:'image/png',buffer:Buffer.from('bad image')});await expect(page.locator('.toast')).toContainText('损坏.png');await expect(editor().locator('.column-selection')).toHaveCount(3);const png=Buffer.from(await app.evaluate(({nativeImage})=>Array.from(nativeImage.createFromBitmap(Buffer.alloc(32*24*4,255),{width:32,height:24}).toPNG())));await page.locator('input[type=file]').setInputFiles([{name:'一.png',mimeType:'image/png',buffer:png},{name:'二.png',mimeType:'image/png',buffer:png}]);await expect(editor().locator('.image-view')).toHaveCount(2);await expect(editor().locator('.column-selection,.column-caret')).toHaveCount(0);await expect(editor().locator('p')).toHaveText(['abcdef','ghijkl','mnopqr']);await expect.poll(()=>saved().assets.length).toBe(2);saved().assets.forEach(a=>expect(Buffer.from(a.data)).toEqual(png));await page.keyboard.press('Control+z');await expect(editor().locator('.image-view')).toHaveCount(0);await expect.poll(()=>saved().events[0].content_html).not.toContain('asset:');
});
