import {_electron,expect,test,type ElectronApplication,type Page} from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import Database from 'better-sqlite3';
import {DocumentStore} from '../../src/main/storage';
import {clipboardPacket,htmlClipboard,type ClipboardEntry} from '../../src/main/clipboard-format';
let app:ElectronApplication,page:Page,root:string,file:string;
const editor=()=>page.locator('.document-scroller:visible .todo-document');
function rows(){const db=new Database(file,{readonly:true});try{return db.prepare('select * from events order by pos').all() as any[];}finally{db.close();}}
const qtEnv=()=>({...process.env,QT_QPA_PLATFORM:'windows',PATH:'E:\\Qt\\6.8.3\\mingw_64\\bin;E:\\Qt\\Tools\\mingw1310_64\\bin;'+process.env.PATH});
async function qt(mode:string,request:any){const input=path.join(root,`${mode}.json`);await fs.writeFile(input,JSON.stringify(request));return JSON.parse(execFileSync(path.resolve('.cache/qt-compat/qt-compat.exe'),[mode,input],{encoding:'utf8',windowsHide:true,env:qtEnv()}));}
function clipboard(html:string,text?:string){const entries:ClipboardEntry[]=[{name:'HTML Format',data:htmlClipboard(html)}];if(text!==undefined)entries.push({name:'CF_UNICODETEXT',data:Buffer.from(text+'\0','utf16le')});execFileSync(path.resolve('out/main/clipboard-win.exe'),{input:clipboardPacket(entries),windowsHide:true});}
test.beforeEach(async({},info)=>{root=info.outputPath('workspace');await fs.mkdir(root,{recursive:true});file=path.join(root,'富文本互通.tde');const store=new DocumentStore(),doc=store.open(file,true);await store.save({...doc,events:[{id:-1,pos:0,created_at:1750000000,deadline_raw:'',deadline_ts:null,done:0,top_divider:0,content_html:'<p>abcdef</p>',content_text:'abcdef'}]});store.close(doc.handle);const env:NodeJS.ProcessEnv={...process.env,TODOLINE_TEST:'1',TODOLINE_DATA_DIR:path.join(root,'profile')};delete env.ELECTRON_RUN_AS_NODE;app=await _electron.launch({args:[path.resolve('.'),'--open',file],env:env as Record<string,string>});page=await app.firstWindow();await app.evaluate(({BrowserWindow})=>{BrowserWindow.getAllWindows()[0].show();BrowserWindow.getAllWindows()[0].focus();});await expect(editor()).toBeVisible();await editor().evaluate((el:any)=>{el.editor.commands.setTextSelection(3);el.editor.view.focus();});});
test.afterEach(async({},info)=>{if(info.status!==info.expectedStatus)await page?.screenshot({path:info.outputPath('failure.png')}).catch(()=>{});await app?.evaluate(({app})=>app.exit(0)).catch(()=>{});});
test('actual Qt text copy preserves rich marks, lists and safe links through native clipboard and SQLite',async({},info)=>{
  const source='<p style="margin-top:0;margin-bottom:0"><b>加粗</b>、<i>斜体</i>、<a href="https://example.com">链接</a></p><ol start="3"><li style="margin-top:0;margin-bottom:0">列表甲</li><li style="margin-top:0;margin-bottom:0">列表乙</li></ol>',copied=await qt('copy-rich',{html:source});expect(copied.richText).toBe(true);expect(copied.text).toContain('列表甲');expect(copied.html.match(/<li\b/g)).toHaveLength(2);expect(await app.evaluate(({clipboard})=>clipboard.has('application/x-tde-richtext'))).toBe(true);await page.keyboard.press('Control+v');await expect(editor().locator('strong')).toContainText('加粗');await expect(editor().locator('em')).toContainText('斜体');await expect(editor().locator('ol')).toHaveAttribute('start','3');await expect(editor().locator('ol > li')).toHaveText(['列表甲','列表乙cdef']);await expect(editor().locator('a')).toHaveAttribute('href','https://example.com');await expect.poll(()=>rows()[0].content_text).toContain('列表乙');await page.screenshot({path:info.outputPath('qt-rich-paste.png')});await page.keyboard.press('Control+z');await expect(editor()).toHaveText('abcdef');await expect.poll(()=>rows()[0].content_text).toBe('abcdef');
});
test('external text stays plain while HTML-only paste follows the original Qt rich path',async()=>{
  const html='<p><b>中文</b><i>正文</i></p>';const plain=await qt('paste-rich',{html,text:'中文正文'});clipboard(html,'中文正文');await page.keyboard.press('Control+v');await expect(editor()).toHaveText(plain.text);await expect(editor().locator('strong,em')).toHaveCount(0);await page.keyboard.press('Control+z');const rich=await qt('paste-rich',{html});clipboard(html);await page.keyboard.press('Control+v');await expect(editor()).toHaveText(rich.text);await expect(editor().locator('strong')).toHaveText('中文');await expect(editor().locator('em')).toHaveText('正文');
});
test('HTML embedded images save exact bytes and display dimensions and undo as one insertion',async({},info)=>{
  const png=Buffer.from(await app.evaluate(({nativeImage})=>Array.from(nativeImage.createFromBitmap(Buffer.alloc(32*24*4,255),{width:32,height:24}).toPNG())));clipboard(`<p><b>图前</b><img src="data:image/png;base64,${png.toString('base64')}" width="16" /><img src="data:image/png;base64,${png.toString('base64')}" height="12" />图后</p>`);await page.keyboard.press('Control+v');await expect(editor().locator('.image-view')).toHaveCount(2);await expect(editor()).toHaveText('ab图前图后cdef');await expect.poll(()=>rows()[0].content_html).toContain('asset:');const db=new Database(file,{readonly:true});try{const assets=db.prepare('select * from assets').all() as any[];expect(assets).toHaveLength(2);assets.forEach(a=>{expect(Buffer.from(a.data)).toEqual(png);expect([a.w,a.h]).toEqual([32,24]);});}finally{db.close();}expect(await editor().evaluate((el:any)=>{const images:any[]=[];el.editor.state.doc.descendants((n:any)=>{if(n.type.name==='image')images.push([n.attrs.width,n.attrs.height]);});return images;})).toEqual([[16,12],[16,12]]);await page.screenshot({path:info.outputPath('embedded-images.png')});await page.keyboard.press('Control+z');await expect(editor()).toHaveText('abcdef');await expect(editor().locator('.image-view')).toHaveCount(0);
});
test('unresolved Qt assets preserve the complete selected document and allow retry',async()=>{
  await page.keyboard.press('Control+a');await qt('copy-rich',{html:'<p>源文件<img src="asset:1" /></p>'});await page.keyboard.press('Control+v');await expect(page.getByText(/剪贴板只有旧版图片引用/)).toBeVisible();await expect(editor()).toHaveText('abcdef');expect(rows()[0].content_text).toBe('abcdef');
  await page.getByRole('button',{name:'关闭消息'}).click();await editor().focus();clipboard('<p><b>重试内容</b></p>');await page.keyboard.press('Control+v');await expect(editor()).toHaveText('重试内容');await expect(editor().locator('strong')).toHaveText('重试内容');await page.keyboard.press('Control+z');await expect(editor()).toHaveText('abcdef');
});
test('inert HTML parsing cannot fetch source resources or execute handlers',async()=>{
  const requests:string[]=[];page.on('request',request=>{if(request.url().includes('example.com'))requests.push(request.url());});clipboard('<p onclick="window.clipboardExecuted=true"><b>安全文字</b><a href="javascript:window.clipboardExecuted=true">链接</a></p><style>@import url(https://example.com/css);</style><script>window.clipboardExecuted=true</script>');await page.keyboard.press('Control+v');await expect(editor()).toHaveText('ab安全文字链接cdef');expect(await page.evaluate(()=>(window as any).clipboardExecuted)).toBeUndefined();expect(requests).toEqual([]);expect(await editor().locator('a').count()).toBe(0);
});
test('rich clipboard tables and Chinese embedded images export to PDF with the folder prompt',async({},info)=>{
  const png=Buffer.from(await app.evaluate(({nativeImage})=>Array.from(nativeImage.createFromBitmap(Buffer.alloc(32*24*4,255),{width:32,height:24}).toPNG())));await page.keyboard.press('Control+a');clipboard(`<table border="1"><tr><td colspan="2"><b>中文表格</b></td></tr><tr><td>图片<img src="data:image/png;base64,${png.toString('base64')}" width="16" /></td><td>正文</td></tr></table>`);await page.keyboard.press('Control+v');await expect(editor().locator('table')).toHaveCount(1);await expect(editor().locator('td[colspan="2"]')).toHaveText('中文表格');await expect(editor().locator('.image-view')).toHaveCount(1);await expect.poll(()=>rows()[0].content_html).toContain('asset:');
  const out=path.join(root,'富文本导出.pdf');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},out);await page.getByRole('button',{name:'导出',exact:true}).click();await page.getByRole('button',{name:'PDF 文档 .pdf',exact:true}).click();await expect.poll(async()=>fs.stat(out).then(s=>s.size,()=>0)).toBeGreaterThan(500);await expect(page.getByRole('dialog',{name:'导出完成'})).toContainText('富文本导出.pdf');await page.screenshot({path:info.outputPath('rich-table.png')});
});
test('HTML-only malformed image batches do not add assets or erase the selection',async()=>{
  const png=Buffer.from(await app.evaluate(({nativeImage})=>Array.from(nativeImage.createFromBitmap(Buffer.alloc(32*24*4,255),{width:32,height:24}).toPNG())));await page.keyboard.press('Control+a');clipboard(`<p>图片<img src="data:image/png;base64,${png.toString('base64')}" /><img src="data:image/png;base64,AQI=" /></p>`);await page.keyboard.press('Control+v');await expect(page.locator('.toast')).toBeVisible();await expect(editor()).toHaveText('abcdef');const db=new Database(file,{readonly:true});try{expect(db.prepare('select count(*) as n from assets').get()).toEqual({n:0});}finally{db.close();}await page.getByRole('button',{name:'关闭消息'}).click();await editor().focus();clipboard('<p><b>正确重试</b></p>');await page.keyboard.press('Control+v');await expect(editor()).toHaveText('正确重试');await page.keyboard.press('Control+z');await expect(editor()).toHaveText('abcdef');
});
test('Qt rich clipboard saved by Electron retains formatting after Qt edits the file again',async()=>{
  await qt('copy-rich',{html:'<p><b>加粗中文</b><i>斜体</i></p>'});await page.keyboard.press('Control+v');await expect(editor().locator('strong')).toHaveText('加粗中文');await expect.poll(()=>rows()[0].content_text).toContain('加粗中文');await app.evaluate(({app})=>app.exit(0));execFileSync(path.resolve('.cache/qt-compat/qt-compat.exe'),['edit',file],{windowsHide:true,env:{...qtEnv(),QT_QPA_PLATFORM:'offscreen'}});
  const env:NodeJS.ProcessEnv={...process.env,TODOLINE_TEST:'1',TODOLINE_DATA_DIR:path.join(root,'profile')};delete env.ELECTRON_RUN_AS_NODE;app=await _electron.launch({args:[path.resolve('.'),'--open',file],env:env as Record<string,string>});page=await app.firstWindow();await expect(editor().locator('strong')).toHaveText('加粗中文');await expect(editor().locator('em')).toHaveText('斜体');await expect(editor()).toContainText('旧版再次编辑');await expect(editor().locator('.legacy-content')).toHaveCount(0);
});
test('standalone numbered and bullet lists keep every item when pasted into text or replacing all content',async({},info)=>{
  for(const tag of ['ol','ul']){clipboard(`<${tag}><li>第一项</li><li>第二项</li></${tag}>`);await page.keyboard.press('Control+v');await expect(editor().locator(`${tag} > li`)).toHaveText(['第一项','第二项cdef']);await page.keyboard.press('Control+z');await expect(editor()).toHaveText('abcdef');await page.keyboard.press('Control+a');await page.keyboard.press('Control+v');await expect(editor().locator(`${tag} > li`)).toHaveText(['第一项','第二项']);await expect.poll(()=>rows()[0].content_text).toContain('第二项');await page.screenshot({path:info.outputPath(`${tag}-paste.png`)});await page.keyboard.press('Control+z');await expect(editor()).toHaveText('abcdef');await editor().evaluate((el:any)=>{el.editor.commands.setTextSelection(3);el.editor.view.focus();});}
});
