import {_electron,expect,test,type ElectronApplication,type Page} from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import Database from 'better-sqlite3';
let app:ElectronApplication,page:Page,root:string,file:string;
const editor=()=>page.locator('.document-scroller:visible .todo-document');
const table='<table border="1" cellpadding="6" cellspacing="0" width="480" style="border-color:#3b82b6;border-style:solid"><tr><td colspan="2" bgcolor="#fff1b8" style="vertical-align:middle"><p><b>标题</b></p></td><td width="160"><p>甲</p></td></tr><tr><td rowspan="2" width="160"><p>跨行</p><p>次段</p></td><td width="160"><p>乙</p></td><td><p>丙</p></td></tr><tr><td><p>丁</p></td><td><p>戊</p></td></tr></table>';
function saved(){const db=new Database(file,{readonly:true});try{return db.prepare('select * from events order by pos').all() as any[];}finally{db.close();}}
function qt(mode:string,input?:string){execFileSync(path.resolve('.cache/qt-compat/qt-compat.exe'),[mode,file,...(input?[input]:[])],{windowsHide:true,env:{...process.env,QT_QPA_PLATFORM:'offscreen',PATH:'E:\\Qt\\6.8.3\\mingw_64\\bin;E:\\Qt\\Tools\\mingw1310_64\\bin;'+process.env.PATH}});}
async function reopen(){await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},file);await page.getByRole('button',{name:'打开文档 · Ctrl+O',exact:true}).click();await expect(editor().locator('table')).toBeVisible();}
async function caret(text:string,offset=0){await editor().evaluate((el:any,args)=>{let pos=-1;el.editor.state.doc.descendants((n:any,p:number)=>{if(n.isText&&n.text===args.text)pos=p+args.offset;});if(pos<0)throw new Error('Missing text');el.editor.commands.setTextSelection(pos);el.editor.view.focus();},{text,offset});await expect(editor()).toBeFocused();}
async function menu(){await page.getByRole('button',{name:'段落与字符格式',exact:true}).click();await page.getByRole('button',{name:'表格…',exact:true}).click();await expect(page.getByLabel('表格操作')).toBeVisible();}
test.beforeEach(async({},info)=>{root=info.outputPath('workspace');await fs.mkdir(root,{recursive:true});file=path.join(root,'Qt表格.tde');const input=path.join(root,'table.html');await fs.writeFile(input,'<p>表格前</p>'+table+'<p>表格后</p>');qt('create-html',input);const env:NodeJS.ProcessEnv={...process.env,TODOLINE_TEST:'1',TODOLINE_DATA_DIR:path.join(root,'profile')};delete env.ELECTRON_RUN_AS_NODE;app=await _electron.launch({args:[path.resolve('.'),'--open',file],env:env as Record<string,string>});page=await app.firstWindow();await app.evaluate(({BrowserWindow})=>{BrowserWindow.getAllWindows()[0].show();BrowserWindow.getAllWindows()[0].focus();});await expect(editor()).toBeVisible();});
test.afterEach(async({},info)=>{if(info.status!==info.expectedStatus)await page?.screenshot({path:info.outputPath('failure.png')}).catch(()=>{});await app?.evaluate(({app})=>app.exit(0)).catch(()=>{});});
test('Qt tables stay byte-identical while browsing and retain layout after editing in both apps',async({},info)=>{
  const before=await fs.readFile(file),original=saved()[0];await expect(editor().locator('.legacy-content')).toHaveCount(0);await expect(editor().locator('tr')).toHaveCount(3);await expect(editor().locator('td')).toHaveCount(7);await caret('乙');await page.keyboard.press('Control+a');await page.keyboard.press('ArrowRight');await page.waitForTimeout(800);expect(await fs.readFile(file)).toEqual(before);
  await caret('乙',1);await page.keyboard.type(' changed');await expect.poll(()=>saved()[0].content_html).toContain('changed');expect(saved()[0]).toMatchObject({id:original.id,created_at:original.created_at,deadline_raw:original.deadline_raw,done:original.done});await page.screenshot({path:info.outputPath('qt-table.png')});
  await page.locator('.file-tab.active .tab-close').click();qt('edit');await reopen();await expect(editor().locator('table')).toHaveAttribute('width','480');await expect(editor().locator('td[colspan="2"]')).toHaveCSS('background-color','rgb(255, 241, 184)');await expect(editor().locator('td[rowspan="2"]')).toContainText('跨行');await expect(editor()).toContainText('changed');await expect(editor()).toContainText('旧版再次编辑');
});
test('table controls, Tab navigation, gutter row selection and undo work in a narrow window',async({},info)=>{
  await caret('乙');await menu();await page.getByRole('button',{name:'在下方插入行',exact:true}).click();await expect(editor().locator('tr')).toHaveCount(4);await page.keyboard.press('Escape');await page.keyboard.press('Control+z');await expect(editor().locator('tr')).toHaveCount(3);
  await caret('戊',1);await page.keyboard.press('Tab');await expect(editor().locator('tr')).toHaveCount(4);await page.keyboard.type('新行');await expect(editor().locator('tr').last()).toContainText('新行');await page.keyboard.press('Control+z');await page.keyboard.press('Control+z');await expect(editor().locator('tr')).toHaveCount(3);
  const gutter=page.locator('.document-scroller:visible .line-label');await expect(gutter).toHaveCount(6);const tops=await gutter.evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().top));expect(tops.every((top,i)=>!i||top>tops[i-1]+1)).toBe(true);await page.getByRole('button',{name:'第 3 行',exact:true}).click();await expect(editor().locator('.selectedCell')).toHaveCount(2);await page.keyboard.press('Delete');await expect(editor()).not.toContainText('标题');await page.keyboard.press('Control+z');await expect(editor()).toContainText('标题');
  await caret('乙');await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(820,680));await menu();const box=await page.locator('.table-menu').boundingBox();expect(box!.y+box!.height).toBeLessThanOrEqual(await page.evaluate(()=>innerHeight));await page.screenshot({path:info.outputPath('table-menu.png')});
});
test('Ctrl+H inside a merged cell saves two rectangular tables and undo restores the source',async()=>{
  const before=await editor().evaluate((el:any)=>el.editor.state.doc.textContent);await caret('跨行',1);await page.keyboard.press('Control+h');await expect(editor().locator(':scope > table')).toHaveCount(2);await expect.poll(()=>saved().length).toBe(2);expect(await editor().evaluate((el:any)=>el.editor.state.doc.textContent)).toBe(before);for(const e of saved())expect(e.content_html).toContain('<table');await page.keyboard.press('Control+z');await expect(editor().locator('table')).toHaveCount(1);await expect.poll(()=>saved().length).toBe(1);await expect(editor().locator('td[rowspan="2"]')).toContainText('跨行');
});
test('table export preserves merged cells in Markdown and includes Chinese and images in PDF',async()=>{
  const png=await app.evaluate(({nativeImage})=>{const pixels=Buffer.alloc(100*60*4);for(let i=0;i<pixels.length;i+=4){pixels[i]=32;pixels[i+1]=128;pixels[i+2]=240;pixels[i+3]=255;}return Array.from(nativeImage.createFromBitmap(pixels,{width:100,height:60}).toPNG());});
  const asset=await page.evaluate(async png=>{const doc=await window.desktop.openRecent((await window.desktop.session()).tabs[0].path);return window.desktop.addAsset(doc.handle,new Uint8Array(png),100,60);},png);await caret('乙',1);await editor().evaluate((el:any,id)=>el.editor.commands.insertContent({type:'image',attrs:{assetId:id,width:100,height:60}}),asset);await expect(editor().locator('td .image-view')).toHaveCount(1);await expect.poll(()=>saved()[0].content_html).toContain('asset:');
  for(const [ext,label] of [['md','Markdown .md'],['txt','纯文本 .txt'],['pdf','PDF 文档 .pdf']] as const){const out=path.join(root,'表格导出.'+ext);await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},out);await page.getByRole('button',{name:'导出',exact:true}).click();await page.getByRole('button',{name:label,exact:true}).click();await expect.poll(()=>fs.stat(out).then(s=>s.size,()=>0)).toBeGreaterThan(100);await expect(page.getByRole('dialog',{name:'导出完成'})).toContainText('表格导出.'+ext);await page.getByRole('button',{name:'知道了',exact:true}).click();if(ext==='md'){const text=await fs.readFile(out,'utf8');expect(text).toContain('colspan="2"');expect(text).toContain('rowspan="2"');expect(text).toContain('[图片]');}if(ext==='txt')expect(await fs.readFile(out,'utf8')).toContain('跨行 / 次段');}
});
test('native cut and cross-file paste preserve a merged table row and undo restores source cells',async()=>{
  await page.getByRole('button',{name:'第 3 行',exact:true}).click();await page.keyboard.press('Control+x');await expect(editor()).not.toContainText('标题');await expect(editor().locator('td')).toHaveCount(7);
  await page.getByRole('button',{name:'新建文档 · Ctrl+N',exact:true}).click();await expect(page.locator('.file-tab.active')).toContainText(/\d{8}_\d+/);await editor().click();await page.keyboard.press('Control+v');await expect(editor().locator('table')).toHaveCount(1);await expect(editor().locator('td[colspan="2"]')).toHaveText('标题');await expect(editor().locator('td')).toHaveCount(2);await expect(editor()).toContainText('甲');
  await page.keyboard.press('Control+z');await expect(editor().locator('table')).toHaveCount(0);await page.locator('.tab-name').first().click();await editor().click();await page.keyboard.press('Control+z');await expect(editor().locator('td[colspan="2"]')).toHaveText('标题');await expect.poll(()=>saved()[0].content_html).toContain('标题');
});
