import {_electron,expect,test,type ElectronApplication,type Page} from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import Database from 'better-sqlite3';
import {DocumentStore} from '../../src/main/storage';
let app:ElectronApplication,page:Page,root:string,file:string;
const html='<table width="400" border="1" cellpadding="6" cellspacing="0"><tr><td colspan="2">标题</td></tr><tr><td width="180" rowspan="2">左</td><td width="220">右</td></tr><tr><td>末尾</td></tr></table><p>尾部正文</p>';
const editor=()=>page.locator('.document-scroller:visible .todo-document');
function saved(){const db=new Database(file,{readonly:true});try{return db.prepare('select content_html from events order by pos').get() as {content_html:string};}finally{db.close();}}
async function start(source=html){const store=new DocumentStore(),doc=store.open(file,true);await store.save({...doc,events:[{id:-1,pos:0,created_at:1750000000,deadline_raw:'',deadline_ts:null,done:0,top_divider:0,content_html:source,content_text:'标题左右末尾\n尾部正文'}]});store.close(doc.handle);const env:NodeJS.ProcessEnv={...process.env,TODOLINE_TEST:'1',TODOLINE_DATA_DIR:path.join(root,'profile')};delete env.ELECTRON_RUN_AS_NODE;app=await _electron.launch({args:[path.resolve('.'),'--open',file],env:env as Record<string,string>});page=await app.firstWindow();await expect(editor()).toBeVisible();await app.evaluate(({BrowserWindow})=>{BrowserWindow.getAllWindows()[0].show();BrowserWindow.getAllWindows()[0].focus();});}
async function begin(delta=50,rtl=false,name='左'){const cell=editor().getByRole('cell',{name,exact:true}),box=(await cell.boundingBox())!,x=rtl?box.x+1:box.x+box.width-1,y=box.y+Math.min(12,box.height/2);await page.mouse.move(x,y);await expect(page.locator('.table-resize-hover')).toHaveCount(1);await page.mouse.down();await page.mouse.move(x+delta*(rtl?-1:1),y,{steps:4});await expect(page.locator('.table-resize-guide')).toBeVisible();return {cell,before:box.width};}
async function reopen(qt=false){await page.locator('.file-tab.active .tab-close').click();await expect(page.locator('.file-tab')).toHaveCount(0);if(qt)execFileSync(path.resolve('.cache/qt-compat/qt-compat.exe'),['edit',file],{windowsHide:true,env:{...process.env,QT_QPA_PLATFORM:'offscreen',PATH:'E:/Qt/6.8.3/mingw_64/bin;E:/Qt/Tools/mingw1310_64/bin;'+process.env.PATH}});await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},file);await page.getByRole('button',{name:'打开文档 · Ctrl+O',exact:true}).click();await expect(editor()).toBeVisible();}
test.beforeEach(async({},info)=>{root=info.outputPath('workspace');file=path.join(root,'列宽.tde');await fs.mkdir(root,{recursive:true});});
test.afterEach(async({},info)=>{if(info.status!==info.expectedStatus)await page?.screenshot({path:info.outputPath('failure.png')}).catch(()=>{});await app?.evaluate(({app})=>app.exit(0)).catch(()=>{});});
test('dragging a column preserves spanned cells, commits once and retains the width through Qt reopening',async({},info)=>{
  await start();const {cell,before}=await begin();expect(saved().content_html).toBe(html);await page.screenshot({path:info.outputPath('width-guide.png')});await page.mouse.up();await expect.poll(()=>cell.boundingBox().then(b=>b!.width)).toBeGreaterThan(before+30);await expect.poll(()=>saved().content_html).not.toBe(html);const changed=saved().content_html;expect(changed).toContain('rowspan="2"');expect(changed).toContain('colspan="2"');const width=(await cell.boundingBox())!.width;await editor().focus();await page.keyboard.press('Control+z');await expect.poll(()=>saved().content_html).toBe(html);await page.keyboard.press('Control+y');await expect.poll(()=>saved().content_html).toBe(changed);await reopen();expect(Math.abs((await editor().getByRole('cell',{name:'左',exact:true}).boundingBox())!.width-width)).toBeLessThan(4);await reopen(true);await expect(editor()).toContainText('旧版再次编辑');expect(Math.abs((await editor().getByRole('cell',{name:'左',exact:true}).boundingBox())!.width-width)).toBeLessThan(6);await page.screenshot({path:info.outputPath('resized-qt.png')});
});
test('Escape cancels a drag without changing selection, history or file bytes',async()=>{await start();await editor().getByText('尾部正文',{exact:true}).click();const selection=await editor().evaluate((el:any)=>el.editor.state.selection.toJSON());await begin();await page.keyboard.press('Escape');await page.mouse.up();await expect(page.locator('.table-resize-guide')).toBeHidden();expect(saved().content_html).toBe(html);expect(await editor().evaluate((el:any)=>el.editor.state.selection.toJSON())).toEqual(selection);});
test('losing the window focus cancels the drag and the next drag remains usable',async()=>{await start();await begin();await app.evaluate(async({BrowserWindow})=>{const parent=BrowserWindow.getAllWindows()[0],child=new BrowserWindow({parent,modal:true,width:200,height:100,show:false});(globalThis as any).resizeParent=parent;(globalThis as any).resizeChild=child;await child.loadURL('about:blank');child.show();child.focus();});await expect(page.locator('.table-resize-guide')).toBeHidden();await page.mouse.up();expect(saved().content_html).toBe(html);await app.evaluate(({BrowserWindow})=>{(globalThis as any).resizeChild.destroy();(globalThis as any).resizeParent.focus();});await begin();await page.mouse.up();await expect.poll(()=>saved().content_html).not.toBe(html);});
test('RTL column edges resize in the mirrored direction and retain text',async()=>{await start(html.replace('<table ','<table style="direction:rtl" '));const {cell,before}=await begin(50,true);await page.mouse.up();await expect.poll(()=>cell.boundingBox().then(b=>b!.width)).toBeGreaterThan(before+30);await expect(editor()).toContainText('尾部正文');});
test('a click without motion keeps original HTML and a merged-cell edge can resize the final column',async()=>{await start();await begin(0);await page.mouse.up();expect(saved().content_html).toBe(html);const {cell,before}=await begin(45,false,'标题');await page.mouse.up();await expect.poll(()=>cell.boundingBox().then(b=>b!.width)).toBeGreaterThan(before+25);});
test('consecutive drags have separate undo steps after both changes were saved',async()=>{await start();await begin(40);await page.mouse.up();await expect.poll(()=>saved().content_html).not.toBe(html);const first=saved().content_html;await begin(-20);await page.mouse.up();await expect.poll(()=>saved().content_html).not.toBe(first);await editor().focus();await page.keyboard.press('Control+z');await expect.poll(()=>saved().content_html).toBe(first);await page.keyboard.press('Control+z');await expect.poll(()=>saved().content_html).toBe(html);});
test('full-width tables redistribute adjacent columns and clamp the neighbour to a usable minimum',async()=>{await start(html.replace('width="400"','width="100%"'));const before=(await editor().locator('table').boundingBox())!.width;const {cell,before:column}=await begin(50);await page.mouse.up();await expect.poll(()=>cell.boundingBox().then(b=>b!.width)).toBeGreaterThan(column+30);expect(Math.abs((await editor().locator('table').boundingBox())!.width-before)).toBeLessThan(4);await begin(10000);await page.mouse.up();expect((await editor().getByRole('cell',{name:'右',exact:true}).boundingBox())!.width).toBeGreaterThanOrEqual(35);await expect(editor()).toContainText('尾部正文');});
test('typing during a drag cancels the preview and preserves the typed content',async()=>{await start();await editor().getByText('尾部正文',{exact:true}).click();await begin();await page.keyboard.type('新增');await page.mouse.up();await expect(page.locator('.table-resize-guide')).toBeHidden();await expect.poll(()=>saved().content_html).toContain('新增');await expect(editor().locator('table')).toHaveAttribute('width','400');});
for(const layout of ['separate','spaced','collapsed'])test(`repeated internal drags do not accumulate border or spacing width: ${layout}`,async()=>{await start(layout==='spaced'?html.replace('cellspacing="0"','cellspacing="6"'):layout==='collapsed'?html.replace('<table ','<table style="border-collapse:collapse" '):html);const geometry=()=>editor().locator('table').evaluate(el=>({rect:el.getBoundingClientRect().width,css:getComputedStyle(el).width,box:getComputedStyle(el).boxSizing,border:getComputedStyle(el).borderLeftWidth,attr:el.getAttribute('width')}));const before=await geometry();for(let i=0;i<6;i++){await begin(i%2?-20:20);await page.mouse.up();}const after=await geometry();expect(Math.abs(after.rect-before.rect),JSON.stringify({before,after})).toBeLessThan(2);});
