import {_electron,expect,test,type ElectronApplication,type Page} from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import Database from 'better-sqlite3';
import {DocumentStore} from '../../src/main/storage';
let app:ElectronApplication,page:Page,root:string,file:string;
const html='<table border="1" cellpadding="6" cellspacing="0" width="500"><tr><td><b>甲</b></td><td>乙</td></tr><tr><td>丙</td><td>丁</td></tr><tr><td>戊</td><td>己</td></tr><tr><td>庚</td><td>辛</td></tr><tr><td>壬</td><td>癸</td></tr></table><p>尾部正文</p>';
const editor=()=>page.locator('.document-scroller:visible .todo-document');
const line=(n:number)=>page.locator('.document-scroller:visible').getByRole('button',{name:`第 ${n} 行`,exact:true});
function saved(){const db=new Database(file,{readonly:true});try{return db.prepare('select content_html from events order by pos').get() as {content_html:string};}finally{db.close();}}
async function rows(){return editor().evaluate((el:any)=>el.editor.state.selection.toJSON().rows??[]);}
async function choose(){await line(1).click();await line(3).click({modifiers:['Control']});await expect.poll(rows).toEqual([0,2]);await expect(page.locator('.table-row-count')).toContainText('已选 2 行');}
async function menu(){await page.getByRole('button',{name:'段落与字符格式',exact:true}).click();await page.getByRole('button',{name:'表格…',exact:true}).click();}
test.beforeEach(async({},info)=>{root=info.outputPath('workspace');file=path.join(root,'非连续行.tde');await fs.mkdir(root,{recursive:true});const store=new DocumentStore(),doc=store.open(file,true);await store.save({...doc,events:[{id:-1,pos:0,created_at:1750000000,deadline_raw:'',deadline_ts:null,done:0,top_divider:0,content_html:html,content_text:'表格'}]});store.close(doc.handle);const env:Record<string,string|undefined>={...process.env,TODOLINE_TEST:'1',TODOLINE_DATA_DIR:path.join(root,'profile')};delete env.ELECTRON_RUN_AS_NODE;app=await _electron.launch({args:[path.resolve('.'),'--open',file],env:env as Record<string,string>});page=await app.firstWindow();await expect(editor()).toBeVisible();await app.evaluate(({BrowserWindow})=>{BrowserWindow.getAllWindows()[0].show();BrowserWindow.getAllWindows()[0].focus();});});
test.afterEach(async({},info)=>{if(info.status!==info.expectedStatus)await page?.screenshot({path:info.outputPath('failure.png')}).catch(()=>{});await app?.evaluate(({app})=>app.exit(0)).catch(()=>{});});
test('Ctrl row selection copies and clears exact rows, saves and undoes once',async({},info)=>{await choose();await expect(editor().locator('.selectedCell')).toHaveCount(4);await expect(page.locator('.line-label.selected')).toHaveCount(2);expect(saved().content_html).toBe(html);await page.screenshot({path:info.outputPath('selected-rows.png')});await page.keyboard.press('Control+c');await expect.poll(()=>app.evaluate(({clipboard})=>clipboard.readText())).toBe('甲\t乙\n戊\t己');await page.keyboard.press('Delete');await expect(editor().locator('tr')).toHaveText(['','丙丁','','庚辛','壬癸']);await expect.poll(()=>saved().content_html).not.toBe(html);await page.keyboard.press('Control+z');await expect.poll(()=>saved().content_html).toBe(html);await expect.poll(rows).toEqual([0,2]);});
test('delete selected rows keeps skipped rows and survives Qt editing',async({},info)=>{await choose();await menu();await page.getByRole('button',{name:'删除选中行',exact:true}).click();await page.keyboard.press('Escape');await expect(editor().locator('tr')).toHaveText(['丙丁','庚辛','壬癸']);await expect.poll(()=>saved().content_html).not.toBe(html);await page.locator('.file-tab.active .tab-close').click();await expect(page.locator('.file-tab')).toHaveCount(0);execFileSync(path.resolve('.cache/qt-compat/qt-compat.exe'),['edit',file],{windowsHide:true,env:{...process.env,QT_QPA_PLATFORM:'offscreen',PATH:'E:/Qt/6.8.3/mingw_64/bin;E:/Qt/Tools/mingw1310_64/bin;'+process.env.PATH}});await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},file);await page.getByRole('button',{name:'打开文档 · Ctrl+O',exact:true}).click();await expect(editor().locator('tr')).toHaveText(['丙丁','庚辛','壬癸']);await expect(editor()).toContainText('旧版再次编辑');await page.screenshot({path:info.outputPath('qt-rows.png')});});
test('toggle, Shift and Ctrl drag preserve precise highlighted row membership',async()=>{await choose();await line(1).click({modifiers:['Control']});await expect.poll(rows).toEqual([2]);await line(3).click({modifiers:['Control']});await expect.poll(rows).toEqual([]);await line(2).click();await line(4).click({modifiers:['Shift']});await expect.poll(rows).toEqual([1,2,3]);await line(1).click();const a=(await line(4).boundingBox())!,b=(await line(5).boundingBox())!;await page.keyboard.down('Control');await page.mouse.move(a.x+10,a.y+10);await page.mouse.down();await page.mouse.move(b.x+10,b.y+10,{steps:5});await page.mouse.up();await page.keyboard.up('Control');await expect.poll(rows).toEqual([0,3,4]);});
test('rich paste targets selected rows and splits pasted spans at skipped rows',async({},info)=>{await choose();await app.evaluate(({clipboard})=>{clipboard.clear();clipboard.writeHTML('<table><tr><td rowspan="2"><b>合并</b></td><td>一</td></tr><tr><td>二</td></tr></table>');});await page.keyboard.press('Control+v');await expect(editor().locator('tr')).toHaveText(['合并一','丙丁','二','庚辛','壬癸']);await expect(editor().locator('td[rowspan="2"]')).toHaveCount(0);await expect.poll(()=>saved().content_html).toContain('合并');await page.screenshot({path:info.outputPath('pasted-rows.png')});await page.keyboard.press('Control+z');await expect.poll(()=>saved().content_html).toBe(html);});
test('cut and cross-file paste retain formatting and separate row ordering',async()=>{await choose();await page.keyboard.press('Control+x');await expect(editor().locator('tr')).toHaveText(['','丙丁','','庚辛','壬癸']);await expect.poll(()=>saved().content_html).not.toBe(html);await page.getByRole('button',{name:'新建文档 · Ctrl+N',exact:true}).click();await expect(page.locator('.file-tab.active')).not.toContainText('非连续行');await editor().focus();await page.keyboard.press('Control+v');await expect(editor().locator('tr')).toHaveText(['甲乙','戊己']);await expect(editor().locator('strong')).toHaveText('甲');await page.locator('.file-tab').filter({hasText:'非连续行'}).locator('.tab-name').click();await editor().focus();await page.keyboard.press('Control+z');await expect.poll(()=>saved().content_html).toBe(html);});
test('composition begins at one caret without rebuilding the editor or clearing selected cells',async()=>{await choose();const mounted=await editor().elementHandle();await editor().dispatchEvent('compositionstart');await editor().dispatchEvent('keydown',{key:'Enter',code:'Enter',isComposing:true,bubbles:true});await expect.poll(rows).toEqual([]);expect(saved().content_html).toBe(html);await editor().dispatchEvent('compositionend');expect(await mounted!.evaluate(el=>el.isConnected)).toBe(true);await page.keyboard.type('中文');await expect(editor().locator('tr').first()).toContainText('中文');await expect(editor().locator('tr').nth(2)).toHaveText('戊己');});
test('row selection retains original image bytes and display size across file paste',async()=>{
  const bytes=await app.evaluate(({nativeImage})=>Array.from(nativeImage.createFromBitmap(Buffer.alloc(40*30*4,255),{width:40,height:30}).toPNG()));
  const id=await page.evaluate(async bytes=>{const doc=await window.desktop.openRecent((await window.desktop.session()).tabs[0].path);return window.desktop.addAsset(doc.handle,new Uint8Array(bytes),40,30);},bytes);
  await editor().evaluate((el:any,id)=>{let pos=0;el.editor.state.doc.descendants((n:any,p:number)=>{if(n.isText&&n.text==='戊')pos=p+1;});el.editor.commands.setTextSelection(pos);el.editor.commands.insertContent({type:'image',attrs:{assetId:id,width:20,height:15}});},id);await expect.poll(()=>saved().content_html).toContain('asset:');
  await choose();await page.keyboard.press('Control+c');await expect.poll(()=>app.evaluate(({clipboard})=>clipboard.readBuffer('application/x-tde-events').length)).toBeGreaterThan(0);await page.getByRole('button',{name:'新建文档 · Ctrl+N',exact:true}).click();await expect(page.locator('.file-tab.active')).not.toContainText('非连续行');await editor().focus();await page.keyboard.press('Control+v');await expect(editor().locator('tr')).toHaveCount(2);await expect(editor().locator('.image-view img')).toHaveCSS('width','20px');
  const target=await page.locator('.file-tab.active .tab-name').getAttribute('title');await expect.poll(()=>{const db=new Database(target!,{readonly:true});try{return db.prepare('select content_html from events order by pos').all().map((e:any)=>e.content_html).join('');}finally{db.close();}}).toContain('asset:');
  const db=new Database(target!,{readonly:true});try{const a=db.prepare('select data,w,h from assets').get() as any;expect(Buffer.from(a.data)).toEqual(Buffer.from(bytes));expect([a.w,a.h]).toEqual([40,30]);}finally{db.close();}
});
