// @vitest-environment jsdom
import {expect,it} from 'vitest';
import {assetNumber,imageAssetReferences,remapImageAssets} from '../src/renderer/asset-references';
it('only replaces actual src values and preserves all other original HTML bytes',()=>{const html='<!DOCTYPE HTML><html><head><style>/* asset:1 */</style></head><body><P title="asset:1">asset:1<!-- <img src="asset:90"> --><IMG alt="asset:1" SRC = \'asset&#58;01\' WIDTH="16" data-note="x > y"><img src=asset:2 /></P></body></html>';expect(imageAssetReferences(html).map(r=>r.id)).toEqual([1,2]);expect(remapImageAssets(html,id=>'asset:'+(id+80))).toBe(html.replace('asset&#58;01','asset:81').replace('src=asset:2','src=asset:82'));});
it.each(['script','style','textarea','title','xmp','iframe','noembed','noframes','plaintext'])('ignores image-like strings in raw text element %s',tag=>{const html=`<${tag}><img src="asset:99"></${tag}><img src="asset:1">`;expect(imageAssetReferences(html).map(r=>r.id)).toEqual(tag==='plaintext'?[]:[1]);});
it('ignores template, document head and noscript images just as the content codec does',()=>{const html='<html><head><img src="asset:8"></head><body><template><script>"</template><img src=asset:9>"</script><template><img src=asset:10></template></template><noscript><img src=asset:11></noscript><img src=asset:1></body></html>';expect(imageAssetReferences(html).map(r=>r.id)).toEqual([1]);});
it('honors the first duplicate src and never reads data-src or quoted markup attributes',()=>{const html='<div title=\'<img src="asset:8">\'><img data-src="asset:9" src="asset:2" src="asset:3"></div>';expect(remapImageAssets(html,()=> 'asset:81')).toBe(html.replace('src="asset:2"','src="asset:81"'));});
it.each(['asset:0','asset:-1','asset:9007199254740992','https://example.com/asset:1','asset:1/','asset:1?x'])('does not mistake invalid or non-asset src for a database reference: %s',src=>{expect(imageAssetReferences(`<img src="${src}">`)).toEqual([]);expect(assetNumber(src)).toBeNull();});
it('rewrites sources safely without changing surrounding text, even for unquoted attributes',()=>{expect(remapImageAssets('<p>asset:1<img src=asset:1></p>',()=> 'scheme:a b"&<')).toBe('<p>asset:1<img src=scheme:a&#32;b&quot;&amp;&lt;></p>');});
