// @vitest-environment node
import { expect,it } from 'vitest';
import { htmlClipboard,readHtmlClipboard,bitmapClipboard,clipboardPacket } from '../src/main/clipboard-format';
it('encodes CF_HTML offsets in UTF-8 bytes including Chinese and emoji',()=>{const fragment='<p>中文🙂</p>',bytes=htmlClipboard(fragment),text=bytes.toString('utf8');const offset=(name:string)=>Number(text.match(new RegExp(name+':(\\d+)'))![1]);expect(bytes.subarray(offset('StartFragment'),offset('EndFragment')).toString('utf8')).toBe(fragment);expect(bytes.subarray(offset('StartHTML'),offset('EndHTML')).toString('utf8')).toBe('<html><body><!--StartFragment-->'+fragment+'<!--EndFragment--></body></html>');expect(bytes.at(-1)).toBe(0);});
it('keeps bitmap pixels and encodes a top-down 32-bit DIBV5 with alpha masks',()=>{const pixels=Buffer.from([1,2,3,255,4,5,6,128]),bytes=bitmapClipboard(2,1,pixels);expect(bytes.length).toBe(132);expect(bytes.readInt32LE(8)).toBe(-1);expect(bytes.readUInt32LE(52)).toBe(0xff000000);expect(bytes.subarray(124)).toEqual(pixels);});
it('rejects mismatched image lengths before writing clipboard memory',()=>{expect(()=>bitmapClipboard(10,10,Buffer.alloc(4))).toThrow('无效图片尺寸');});
it('frames multiple formats without modifying their payloads',()=>{const bytes=clipboardPacket([{name:'CF_UNICODETEXT',data:Buffer.from('甲\0','utf16le')},{name:'application/x-tde-events',data:Buffer.from('{"id":1}')}]);expect(bytes.readUInt32LE(0)).toBe(0x50434c54);expect(bytes.readUInt32LE(4)).toBe(2);const name=bytes.readUInt32LE(8),size=bytes.readUInt32LE(12);expect(bytes.subarray(16,16+name).toString()).toBe('CF_UNICODETEXT');expect(bytes.subarray(16+name,16+name+size).toString('utf16le')).toBe('甲\0');});
it('decodes Chinese and emoji by CF_HTML byte offsets, excluding outside context',()=>{expect(readHtmlClipboard(htmlClipboard('<p>中文🙂</p>'))).toBe('<p>中文🙂</p>');expect(readHtmlClipboard(Buffer.alloc(0))).toBe('');});
it.each(['StartFragment:0000000001','EndFragment:9999999999','StartHTML:9999999999','EndHTML:0000000001'])('rejects invalid CF_HTML bounds: %s',bad=>{const data=htmlClipboard('<b>内容</b>').toString('utf8').replace(new RegExp(bad.split(':')[0]+':\\d+'),bad);expect(()=>readHtmlClipboard(Buffer.from(data))).toThrow();});
it('rejects missing offsets, truncated UTF-8 and fragment end before start',()=>{expect(()=>readHtmlClipboard(Buffer.from('<b>raw</b>'))).toThrow();const raw=htmlClipboard('🙂'),text=raw.toString('utf8'),from=Number(/StartFragment:(\d+)/.exec(text)![1]);const invalid=Buffer.from(raw);invalid[from]=0xff;expect(()=>readHtmlClipboard(invalid)).toThrow();expect(()=>readHtmlClipboard(Buffer.from(text.replace(/EndFragment:\d+/,`EndFragment:${String(from-1).padStart(10,'0')}`)))).toThrow();});
it.each(['\r','\n','\r\n'])('accepts a fragment without HTML context with %j header separators',newline=>{const fragment='<p>中文</p>',header=(start:number,end:number)=>['Version:1.0','StartHTML:-1','EndHTML:-1',`StartFragment:${String(start).padStart(10,'0')}`,`EndFragment:${String(end).padStart(10,'0')}`,''].join(newline);const start=Buffer.byteLength(header(0,0));expect(readHtmlClipboard(Buffer.from(header(start,start+Buffer.byteLength(fragment))+fragment))).toBe(fragment);});
