// @vitest-environment jsdom
import {afterEach,beforeAll,expect,it,vi} from 'vitest';
import {TodoEditor} from '../src/renderer/editor';
import {newEvent,exportContents} from '../src/renderer/document';
import {prepareEventClipboard} from '../src/renderer/event-clipboard';
const owners:TodoEditor[]=[];
function setup(html='<p>abcdef</p>'){
  const el=document.createElement('div');document.body.append(el);const error=vi.fn(),asset=vi.fn().mockResolvedValue(81),assets=vi.fn().mockImplementation(async values=>values.map((_:unknown,i:number)=>81+i)),imageInfo=vi.fn().mockResolvedValue({width:32,height:24});
  const owner=new TodoEditor(el,{handle:'event-assets',path:'test.tde',name:'test',revision:0,events:[{...newEvent(),id:1,content_html:html,content_text:html.replace(/<[^>]*>/g,'')}]},{change:vi.fn(),selection:vi.fn(),error,asset,assets,imageInfo});owners.push(owner);owner.editor.view.setProps({handleScrollToSelection:()=>true});owner.editor.commands.setTextSelection(3);return {owner,editor:owner.editor,error,asset,assets,imageInfo};
}
const event=(html:string)=>({created_at:123,deadline_raw:'明天',deadline_ts:456,done:true,top_divider:true,html,text:html.replace(/<[^>]*>/g,'')});
const rawAssets=[{name:'asset:1',data:'AQI=',w:32,h:24},{name:'asset:2',data:'AwQ=',w:32,h:24}];
function clip(payload:unknown){window.desktop={readClipboard:vi.fn().mockResolvedValue({text:'',html:'',events:JSON.stringify(payload)})} as any;}
beforeAll(()=>{Range.prototype.getClientRects=()=>[] as unknown as DOMRectList;Range.prototype.getBoundingClientRect=()=>({left:0,top:0,right:0,bottom:0,width:0,height:0} as DOMRect);});
afterEach(()=>{for(const owner of owners.splice(0))owner.destroy();document.body.innerHTML='';});
it('copies literal asset-like text without requesting an unrelated asset',async()=>{const {owner,editor,error}=setup('<p>示例 asset:123</p>'),copy=vi.fn(),asset=vi.fn().mockResolvedValue(null);window.desktop={copy,asset} as any;editor.commands.selectAll();await owner.copy();expect(error).not.toHaveBeenCalled();expect(copy).toHaveBeenCalledOnce();expect(asset).not.toHaveBeenCalled();expect(JSON.parse(copy.mock.calls[0][0].events).assets).toEqual([]);});
it('pastes literal asset-like text in full events without rewriting it',async()=>{const {owner,error}=setup();clip({events:[event('<p>示例 asset:123</p>')],assets:[]});await owner.paste();expect(error).not.toHaveBeenCalled();expect(owner.records().map(e=>e.content_text).join('')).toContain('asset:123');});
it('validates all event images before storing any of them or deleting selected text',async()=>{const {owner,editor,error,asset,assets,imageInfo}=setup();editor.commands.selectAll();asset.mockResolvedValueOnce(81).mockRejectedValueOnce(new Error('bad second image'));imageInfo.mockResolvedValueOnce({width:32,height:24}).mockRejectedValueOnce(new Error('bad second image'));clip({events:[event('<p><img src="asset:1" /><img src="asset:2" /></p>')],assets:rawAssets});await owner.paste();expect(error).toHaveBeenCalledOnce();expect(asset).not.toHaveBeenCalled();expect(assets).not.toHaveBeenCalled();expect(editor.state.doc.textContent).toBe('abcdef');});
it('checks missing fragment image references before storing assets',async()=>{const {owner,editor,error,asset,assets}=setup();clip({fragment:[{type:'paragraph',content:[{type:'image',attrs:{assetId:1}},{type:'image',attrs:{assetId:99}}]}],assets:rawAssets});await owner.paste();expect(error).toHaveBeenCalled();expect(asset).not.toHaveBeenCalled();expect(assets).not.toHaveBeenCalled();expect(editor.state.doc.textContent).toBe('abcdef');});
it('PDF export keeps literal asset-like text while rewriting actual image sources',()=>{const result=exportContents([{...newEvent(),content_html:'<p>asset:123<img src="asset:1" width="16" height="12" /></p>'}],'pdf','document-handle');expect(result).toContain('>asset:123<img');expect(result).toContain('src="tde-asset://document/document-handle/1"');expect(result).not.toContain('document-handle/123');});
it('stores shared referenced images once, ignores unused bytes, and keeps source dimensions and metadata',async()=>{const {owner,editor,error,asset,assets}=setup();editor.commands.selectAll();clip({events:[event('<p>asset:2<img src="asset:1" width="16" height="12" /></p>'),event('<p>后<img src="asset:1" width="8" height="6" /></p>')],assets:[rawAssets[0],{...rawAssets[1],data:'broken unused data'}]});await owner.paste();expect(error).not.toHaveBeenCalled();expect(asset).not.toHaveBeenCalled();expect(assets).toHaveBeenCalledOnce();expect(assets.mock.calls[0][0]).toEqual([{data:new Uint8Array([1,2]),w:32,h:24}]);const rows=owner.records();expect(rows).toHaveLength(2);expect(rows[0]).toMatchObject({created_at:123,deadline_raw:'明天',deadline_ts:456,done:1,top_divider:1});expect(rows[0].content_html).toContain('asset:2<img');expect(rows[0].content_html).toContain('src="asset:81" width="16" height="12"');expect(rows[1].content_html).toContain('src="asset:81" width="8" height="6"');editor.commands.undo();expect(editor.state.doc.textContent).toBe('abcdef');editor.commands.redo();expect(owner.records()).toHaveLength(2);});
it('preserves literal asset text and nested images in a fragment with one atomic import',async()=>{const {owner,error,assets}=setup();clip({fragment:[{type:'paragraph',content:[{type:'text',text:'asset:1'},{type:'image',attrs:{assetId:1,width:16,height:12}}]}],assets:rawAssets});await owner.paste();expect(error).not.toHaveBeenCalled();expect(assets).toHaveBeenCalledOnce();expect(assets.mock.calls[0][0]).toHaveLength(1);expect(owner.records()[0].content_html).toContain('asset:1<img src="asset:81"');});
it.each([{events:{}},{fragment:{}},{events:[{...event('<p>x</p>'),created_at:'bad'}]},{events:[{...event('<p>x</p>'),deadline_ts:1e30}]},{events:[{...event('<p>x</p>'),done:'false'}]},{fragment:[{type:'paragraph',content:[{type:'image',attrs:{assetId:0}}]}]},{fragment:[{type:'unsupported'}]}])('rejects malformed event or fragment metadata before importing assets: %#',async payload=>{const {owner,editor,error,asset,assets}=setup();clip({...payload,assets:rawAssets});editor.commands.selectAll();await owner.paste();expect(error).toHaveBeenCalled();expect(asset).not.toHaveBeenCalled();expect(assets).not.toHaveBeenCalled();expect(editor.state.doc.textContent).toBe('abcdef');});
it('rejects conflicting aliases of an image ID before decoding or saving',()=>{expect(()=>prepareEventClipboard(JSON.stringify({events:[event('<p><img src=asset:1></p>')],assets:[rawAssets[0],{...rawAssets[1],name:'asset:01'}]}),false)).toThrow('冲突');});
it('keeps unknown event HTML byte-for-byte in the prepared envelope while resolving actual image references',()=>{const html='<!DOCTYPE HTML><html><body><div custom="asset:9"><unknown>asset:9<img src=\'asset:1\' /></unknown></div></body></html>',prepared=prepareEventClipboard(JSON.stringify({events:[event(html)],assets:rawAssets}),true)!;expect(prepared.events[0].content_html).toBe(html);expect(prepared.assets.map(a=>a.id)).toEqual([1]);});
it('a failed batch write preserves the selection and allows a complete retry',async()=>{const {owner,editor,error,assets}=setup();editor.commands.selectAll();const before=editor.state.selection.toJSON();assets.mockRejectedValueOnce(new Error('disk full'));clip({events:[event('<p><img src="asset:1" /></p>')],assets:rawAssets});await owner.paste();expect(error).toHaveBeenCalledOnce();expect(editor.state.selection.toJSON()).toEqual(before);expect(editor.state.doc.textContent).toBe('abcdef');await owner.paste();expect(owner.records()[0].content_html).toContain('asset:81');});
it('rejects changed targets before storing a slow decoded event image',async()=>{const {owner,editor,error,assets,imageInfo}=setup();editor.commands.setTextSelection({from:2,to:5});let resume!:(value:any)=>void;imageInfo.mockImplementationOnce(()=>new Promise(r=>{resume=r;}));clip({events:[event('<p><img src="asset:1" /></p>')],assets:rawAssets});const pending=owner.paste();await vi.waitFor(()=>expect(resume).toBeDefined());editor.commands.insertContent('new');resume({width:32,height:24});await pending;expect(assets).not.toHaveBeenCalled();expect(error).toHaveBeenCalledWith(expect.stringContaining('目标内容已被修改'));expect(editor.state.doc.textContent).toBe('anewef');});
it('rejects an unsupported fragment mark without silently dropping it or storing images',async()=>{const {owner,error,assets}=setup();clip({fragment:[{type:'paragraph',content:[{type:'text',text:'x',marks:[{type:'unknown'}]},{type:'image',attrs:{assetId:1}}]}],assets:rawAssets});await owner.paste();expect(error).toHaveBeenCalled();expect(assets).not.toHaveBeenCalled();});
it('empty internal fragments leave the selected document intact',async()=>{const {owner,editor,error,assets}=setup();editor.commands.selectAll();const selection=editor.state.selection.toJSON();clip({fragment:[],assets:[]});await owner.paste();expect(error).not.toHaveBeenCalled();expect(assets).not.toHaveBeenCalled();expect(editor.state.doc.textContent).toBe('abcdef');expect(editor.state.selection.toJSON()).toEqual(selection);});
it('accepts a real open list fragment copied from a nested item into the following outer item',async()=>{const source=setup('<ul><li><p>outer</p><ul><li><p>inner</p></li></ul></li><li><p>ending</p></li></ul>');let from=0,to=0;source.editor.state.doc.descendants((n,p)=>{if(n.isText&&n.text==='inner')from=p+1;if(n.isText&&n.text==='ending')to=p+2;});source.editor.commands.setTextSelection({from,to});let payload:any;window.desktop={copy:vi.fn(async value=>{payload=value;})} as any;await source.owner.copy();expect(source.error).not.toHaveBeenCalled();const target=setup();window.desktop={readClipboard:vi.fn().mockResolvedValue(payload)} as any;await target.owner.paste();expect(target.error).not.toHaveBeenCalled();expect(target.editor.state.doc.textContent).toContain('nner');expect(target.editor.state.doc.textContent).toContain('en');target.editor.commands.undo();expect(target.editor.state.doc.textContent).toBe('abcdef');});
it('preserves the numbering of copied items beginning in the middle of an ordered list',async()=>{const source=setup('<ol start="3"><li>aaa</li><li>bbb</li><li>ccc</li></ol>');let from=0,to=0;source.editor.state.doc.descendants((n,p)=>{if(n.isText&&n.text==='bbb')from=p+1;if(n.isText&&n.text==='ccc')to=p+2;});source.editor.commands.setTextSelection({from,to});let payload:any;window.desktop={copy:vi.fn(async value=>{payload=value;})} as any;await source.owner.copy();expect(JSON.parse(payload.events).fragment[0].attrs.start).toBe(4);const target=setup();window.desktop={readClipboard:vi.fn().mockResolvedValue(payload)} as any;await target.owner.paste();expect(target.error).not.toHaveBeenCalled();expect(target.owner.records()[0].content_html).toContain('start="4"');});
