// @vitest-environment jsdom
import {afterEach,beforeAll,expect,it,vi} from 'vitest';
import {TodoEditor} from '../src/renderer/editor';
import {newEvent} from '../src/renderer/document';
const owners:TodoEditor[]=[];
function setup(html='<p>abcdef</p>'){
  const el=document.createElement('div');document.body.append(el);const error=vi.fn(),assets=vi.fn().mockResolvedValue([81,82]),imageInfo=vi.fn().mockResolvedValue({width:1200,height:600});
  const owner=new TodoEditor(el,{handle:'files',path:'test.tde',name:'test',revision:0,events:[{...newEvent(),id:1,content_html:html,content_text:'abcdef'}]},{change:vi.fn(),selection:vi.fn(),error,asset:vi.fn(),assets,imageInfo});owners.push(owner);owner.editor.view.setProps({handleScrollToSelection:()=>true});owner.editor.commands.setTextSelection(3);
  window.desktop={readClipboard:vi.fn().mockResolvedValue({text:'',html:'',events:'',images:[{name:'first.png',data:new Uint8Array([1,2])},{name:'second.gif',data:new Uint8Array([3,4])}]})} as any;
  return {owner,editor:owner.editor,error,assets,imageInfo};
}
function images(owner:TodoEditor){const nodes:any[]=[];owner.editor.state.doc.descendants(n=>{if(n.type.name==='image')nodes.push(n.attrs);});return nodes;}
beforeAll(()=>{Range.prototype.getClientRects=()=>[] as unknown as DOMRectList;Range.prototype.getBoundingClientRect=()=>({left:0,top:0,right:0,bottom:0,width:0,height:0} as DOMRect);});
afterEach(()=>{for(const owner of owners.splice(0))owner.destroy();document.body.innerHTML='';});
it('pastes a file batch once at the caret, stores exact bytes together, and undoes/redoes together',async()=>{const {owner,editor,error,assets}=setup();await owner.paste();expect(error).not.toHaveBeenCalled();expect(assets).toHaveBeenCalledOnce();expect(assets.mock.calls[0][0].map((a:any)=>Array.from(a.data))).toEqual([[1,2],[3,4]]);expect(editor.state.doc.textContent).toBe('abcdef');expect(images(owner)).toMatchObject([{assetId:81,width:518,height:259},{assetId:82,width:518,height:259}]);editor.commands.undo();expect(images(owner)).toHaveLength(0);expect(editor.state.doc.textContent).toBe('abcdef');editor.commands.redo();expect(images(owner)).toHaveLength(2);});
it('bad later images preserve the whole selection, add no assets, and allow retry',async()=>{const {owner,editor,error,assets,imageInfo}=setup();editor.commands.selectAll();const selection=editor.state.selection.toJSON();imageInfo.mockResolvedValueOnce({width:32,height:24}).mockRejectedValueOnce(new Error('bad image'));await owner.paste();expect(error).toHaveBeenCalledWith(expect.stringContaining('second.gif'));expect(assets).not.toHaveBeenCalled();expect(editor.state.selection.toJSON()).toEqual(selection);expect(editor.state.doc.textContent).toBe('abcdef');await owner.paste();expect(images(owner)).toHaveLength(2);expect(editor.state.doc.textContent).toBe('');editor.commands.undo();expect(editor.state.doc.textContent).toBe('abcdef');});
it('a failed batch database transaction does not erase selected text',async()=>{const {owner,editor,error,assets}=setup();editor.commands.selectAll();assets.mockRejectedValueOnce(new Error('disk full'));await owner.paste();expect(error).toHaveBeenCalledWith(expect.stringContaining('disk full'));expect(editor.state.doc.textContent).toBe('abcdef');expect(images(owner)).toHaveLength(0);});
it('row highlights do not delete their text on image file paste',async()=>{const {owner,editor}=setup('<p>abcdef</p><p>ghijkl</p>');owner.selectedRanges=[{from:1,to:7,row:true},{from:9,to:15,row:true}];await owner.paste();expect(editor.state.doc.textContent).toBe('abcdefghijkl');expect(images(owner)).toHaveLength(2);expect(owner.selectedRanges).toEqual([]);});
it('protects changed target content while asynchronous file decoding waits',async()=>{const {owner,editor,error,assets,imageInfo}=setup();let resume!:(v:any)=>void;imageInfo.mockImplementationOnce(()=>new Promise(r=>{resume=r;}));editor.commands.setTextSelection({from:2,to:5});const operation=owner.paste();await vi.waitFor(()=>expect(resume).toBeDefined());editor.commands.insertContent('new');resume({width:32,height:24});await operation;expect(error).toHaveBeenCalledWith(expect.stringContaining('目标内容已被修改'));expect(assets).not.toHaveBeenCalled();expect(editor.state.doc.textContent).toBe('anewef');});
it('preserves a later caret and inserts at the captured location',async()=>{const {owner,editor,imageInfo}=setup();let resume!:(v:any)=>void;imageInfo.mockImplementationOnce(()=>new Promise(r=>{resume=r;}));const operation=owner.paste();await vi.waitFor(()=>expect(resume).toBeDefined());editor.commands.setTextSelection(7);resume({width:32,height:24});await operation;expect(editor.state.selection.from).toBe(editor.state.doc.content.size-1);expect(editor.state.doc.firstChild?.child(0).text).toBe('ab');expect(images(owner)).toHaveLength(2);});
