// @vitest-environment jsdom
import {afterEach,beforeAll,expect,it,vi} from 'vitest';
import {TodoEditor} from '../src/renderer/editor';
import {newEvent} from '../src/renderer/document';
import {parseRichClipboard} from '../src/renderer/rich-clipboard';
const owners:TodoEditor[]=[];
function setup(html='<p>abcdef</p>'){
  const el=document.createElement('div');document.body.append(el);const error=vi.fn(),asset=vi.fn().mockResolvedValue(81),assets=vi.fn().mockImplementation(async values=>values.map((_:unknown,i:number)=>81+i)),imageInfo=vi.fn().mockResolvedValue({width:32,height:24});
  const owner=new TodoEditor(el,{handle:'rich',path:'test.tde',name:'test',revision:0,events:[{...newEvent(),id:1,content_html:html,content_text:'abcdef'}]},{change:vi.fn(),selection:vi.fn(),error,asset,assets,imageInfo});owners.push(owner);owner.editor.view.setProps({handleScrollToSelection:()=>true});owner.editor.commands.setTextSelection(3);return {owner,editor:owner.editor,error,asset,assets,imageInfo};
}
function clip(html:string,text='',richText=false){window.desktop={readClipboard:vi.fn().mockResolvedValue({text,html,richText,events:''})} as any;}
beforeAll(()=>{Range.prototype.getClientRects=()=>[] as unknown as DOMRectList;Range.prototype.getBoundingClientRect=()=>({left:0,top:0,right:0,bottom:0,width:0,height:0} as DOMRect);});
afterEach(()=>{for(const owner of owners.splice(0))owner.destroy();document.body.innerHTML='';});
it('keeps external text plain by default even when HTML is available',async()=>{clip('<p><b>粗体</b></p>','粗体');const {owner,editor,error}=setup();await owner.paste();expect(editor.state.doc.textContent).toBe('ab粗体cdef');expect(owner.records()[0].content_html).not.toContain('<b>');expect(error).not.toHaveBeenCalled();});
it.each([false,true])('pastes HTML-only or Qt-marked rich text inline without an extra paragraph: %s',async rich=>{clip('<p><b>粗体</b><i>斜体</i></p>',rich?'粗体斜体':'',rich);const {owner,editor,error}=setup();await owner.paste();expect(editor.state.doc.textContent).toBe('ab粗体斜体cdef');expect(editor.state.doc.childCount).toBe(1);expect(owner.records()[0].content_html).toMatch(/<(b|strong)>粗体/);expect(error).not.toHaveBeenCalled();editor.commands.undo();expect(editor.state.doc.textContent).toBe('abcdef');});
it('does not resolve foreign Qt asset IDs against the current file',async()=>{clip('<p>文字<img src="asset:1" /></p>','文字',true);const {owner,editor,error,assets}=setup();await owner.paste();expect(editor.state.doc.textContent).toBe('abcdef');expect(error).toHaveBeenCalled();expect(assets).not.toHaveBeenCalled();});
it('imports all embedded images atomically and preserves display dimensions',async()=>{clip('<p><b>图前</b><img src="data:image/png;base64,AQI=" width="16" height="12" /><img src="data:image/png;base64,AwQ=" /></p>');const {owner,editor,error,assets}=setup();await owner.paste();expect(error).not.toHaveBeenCalled();expect(assets).toHaveBeenCalledOnce();expect(assets.mock.calls[0][0].map((a:any)=>Array.from(a.data))).toEqual([[1,2],[3,4]]);let images:any[]=[];editor.state.doc.descendants(n=>{if(n.type.name==='image')images.push(n.attrs);});expect(images).toHaveLength(2);expect(images[0]).toMatchObject({assetId:81,width:16,height:12});expect(images[1]).toMatchObject({assetId:82,width:32,height:24});editor.commands.undo();expect(editor.state.doc.textContent).toBe('abcdef');});
it.each(['width="16"','height="12"'])('infers missing image display dimension from original aspect ratio: %s',async attr=>{clip(`<p><img src="data:image/png;base64,AQI=" ${attr} /></p>`);const {owner,editor}=setup();await owner.paste();let attrs:any;editor.state.doc.descendants(n=>{if(n.type.name==='image')attrs=n.attrs;});expect(attrs).toMatchObject({width:16,height:12});});
it('validates the whole image batch before storing any assets, then permits retry',async()=>{clip('<p><img src="data:image/png;base64,AQI=" /><img src="data:image/png;base64,AwQ=" /></p>');const {owner,editor,error,imageInfo,assets}=setup();imageInfo.mockResolvedValueOnce({width:32,height:24}).mockRejectedValueOnce(new Error('bad image'));await owner.paste();expect(assets).not.toHaveBeenCalled();expect(editor.state.doc.textContent).toBe('abcdef');expect(error).toHaveBeenCalledOnce();await owner.paste();expect(assets).toHaveBeenCalledOnce();});
it.each(['<script>window.hacked=true</script><!--comment-->','<html><head><title>title</title></head><body></body></html>'])('empty HTML preserves a nonempty selection: %s',async html=>{clip(html);const {owner,editor,error}=setup();editor.commands.selectAll();const before=editor.state.selection.toJSON();await owner.paste();expect(editor.state.doc.textContent).toBe('abcdef');expect(editor.state.selection.toJSON()).toEqual(before);expect(error).not.toHaveBeenCalled();});
it.each(['<p><img src="https://example.com/private.png" /></p>','<p><img src="file:///C:/private.png" /></p>','<p><img src="data:image/png;base64,A===" /></p>','<iframe src="https://example.com">内容</iframe>'])('rejects unresolved or unsupported rich content without altering selected text: %s',async html=>{clip(html);const {owner,editor,error,assets}=setup();editor.commands.selectAll();await owner.paste();expect(editor.state.doc.textContent).toBe('abcdef');expect(error).toHaveBeenCalledOnce();expect(assets).not.toHaveBeenCalled();});
it('discards active content and preserves safe links without adding live source DOM',()=>{const parsed=parseRichClipboard('<p onclick="bad()"><b>safe</b><a href="javascript:bad()">bad link</a><a href="https://example.com">good link</a></p><script>bad()</script>');expect(JSON.stringify(parsed.content)).not.toMatch(/onclick|javascript:|bad\(\)/);expect(JSON.stringify(parsed.content)).toContain('https://example.com');});
it('uses only the primary caret for rich paste over row/column highlights',async()=>{clip('<p><b>X</b></p>','X',true);const {owner,editor}=setup('<p>abcdef</p><p>ghijkl</p>');owner.selectedRanges=[{from:2,to:4},{from:10,to:12}];editor.commands.setTextSelection(2);await owner.paste();expect(editor.state.doc.textContent).toBe('aXbcdefghijkl');expect(owner.selectedRanges).toEqual([]);});
it('keeps rich code text literal and stays inside the code block',async()=>{clip('<p><b>one</b></p><p>two</p>','one\ntwo',true);const {owner,editor,error}=setup('<pre>abcdef</pre>');await owner.paste();expect(error).not.toHaveBeenCalled();expect(editor.state.doc.childCount).toBe(1);expect(editor.state.doc.firstChild?.type.name).toBe('codeBlock');expect(editor.state.doc.textContent).toBe('abone\ntwocdef');});
it('preserves queued paste order and maps the captured caret while decoding images',async()=>{clip('<p><b>X</b></p>','X',true);const {owner,editor}=setup();const a=owner.paste(),b=owner.paste();await Promise.all([a,b]);expect(editor.state.doc.textContent).toBe('abXXcdef');editor.commands.undo();expect(editor.state.doc.textContent).toBe('abXcdef');});
it('pastes an HTML table as a table without merging its cells into the surrounding paragraph',async()=>{clip('<table><tr><td>A</td><td>B</td></tr></table>');const {owner,editor,error}=setup();await owner.paste();expect(error).not.toHaveBeenCalled();expect(editor.state.doc.content.content.map(n=>n.type.name)).toEqual(['paragraph','table','paragraph']);expect(editor.state.doc.textContent).toBe('abABcdef');expect(owner.records()[0].content_html).toContain('<table');editor.commands.undo();expect(editor.state.doc.textContent).toBe('abcdef');});
it('replaces an event selection with rich HTML and restores metadata on undo',async()=>{clip('<p><b>替换</b></p>','替换',true);const {owner,editor,error}=setup();const before=structuredClone(owner.records());owner.selectEvents([1]);await owner.paste();expect(error).not.toHaveBeenCalled();expect(owner.records()[0].content_text).toBe('替换');expect(owner.records()[0].content_html).toMatch(/<(b|strong)>/);editor.commands.undo();expect(owner.records()).toEqual(before);});
it('does not overwrite edited content while an embedded image is decoding',async()=>{clip('<p><img src="data:image/png;base64,AQI=" /></p>');const {owner,editor,error,imageInfo,assets}=setup();let resolve!:(value:any)=>void;imageInfo.mockImplementationOnce(()=>new Promise(r=>{resolve=r;}));editor.commands.setTextSelection({from:2,to:4});const pasting=owner.paste();await vi.waitFor(()=>expect(imageInfo).toHaveBeenCalled());editor.commands.insertContent('NEW');resolve({width:32,height:24});await pasting;expect(editor.state.doc.textContent).toBe('aNEWdef');expect(assets).not.toHaveBeenCalled();expect(error).toHaveBeenCalledOnce();});
it('keeps a later caret and unrelated edits while the rich target moves',async()=>{clip('<p><img src="data:image/png;base64,AQI=" /></p>');const {owner,editor,error,imageInfo}=setup();let resolve!:(value:any)=>void;imageInfo.mockImplementationOnce(()=>new Promise(r=>{resolve=r;}));const pasting=owner.paste();await vi.waitFor(()=>expect(imageInfo).toHaveBeenCalled());editor.commands.setTextSelection(1);editor.commands.insertContent('Q');resolve({width:32,height:24});await pasting;expect(error).not.toHaveBeenCalled();expect(editor.state.doc.textContent).toBe('Qabcdef');expect(editor.state.selection.from).toBe(2);let pos=0;editor.state.doc.descendants((n,p)=>{if(n.type.name==='image')pos=p;});expect(pos).toBe(4);});
it('does not discard an embedded image when pasting rich content into code',async()=>{clip('<p>图前<img src="data:image/png;base64,AQI=" />图后</p>');const {owner,editor,error}=setup('<pre>abcdef</pre>');await owner.paste();expect(error).not.toHaveBeenCalled();let images=0;editor.state.doc.descendants(n=>{if(n.type.name==='image')images++;});expect(images).toBe(1);expect(editor.state.doc.textContent).toBe('ab图前图后cdef');editor.commands.undo();expect(editor.state.doc.textContent).toBe('abcdef');});
it('preserves both numbered list items when rich content ends in a list',async()=>{clip('<p>前文</p><ol start="3"><li>列表甲</li><li>列表乙</li></ol>');const {owner,editor,error}=setup();await owner.paste();expect(error).not.toHaveBeenCalled();const lists:any[]=[];editor.state.doc.descendants(n=>{if(n.type.name==='orderedList')lists.push(n.toJSON());});expect(lists).toHaveLength(1);expect(lists[0].attrs.start).toBe(3);expect(lists[0].content).toHaveLength(2);expect(lists[0].content[0].content[0].content[0].text).toBe('列表甲');});
it.each(['ol','ul'])('preserves a standalone %s with every list item',async tag=>{clip(`<${tag}><li>甲</li><li>乙</li></${tag}>`);const {owner,editor,error}=setup();await owner.paste();expect(error).not.toHaveBeenCalled();const items:string[]=[];editor.state.doc.descendants(n=>{if(n.type.name==='listItem')items.push(n.textContent);});expect(items).toHaveLength(2);expect(items[0]).toContain('甲');expect(items[1]).toContain('乙');});
it.each(['<p></p>','<p>abcdef</p>'])('retains both list items when replacing the whole document %s',async html=>{clip('<ol start="3"><li>甲</li><li>乙</li></ol>');const {owner,editor,error}=setup(html);editor.commands.selectAll();await owner.paste();expect(error).not.toHaveBeenCalled();expect(editor.state.doc.firstChild?.type.name).toBe('orderedList');expect(editor.state.doc.firstChild?.childCount).toBe(2);expect(editor.state.doc.textContent).toBe('甲乙');});
it.each([['blockquote','<blockquote><p>引用</p></blockquote>'],['codeBlock','<pre>code</pre>'],['heading','<h2>标题</h2>']])('preserves a leading %s wrapper when inserting into normal text',async(kind,html)=>{clip(html);const {owner,editor,error}=setup();await owner.paste();expect(error).not.toHaveBeenCalled();const kinds:string[]=[];editor.state.doc.descendants(n=>{kinds.push(n.type.name);});expect(kinds).toContain(kind);editor.commands.undo();expect(editor.state.doc.textContent).toBe('abcdef');});
