// @vitest-environment jsdom
import {afterEach,beforeAll,describe,expect,it,vi} from 'vitest';
import {existsSync,mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {CellSelection,TableMap} from '@tiptap/pm/tables';
import {TodoEditor} from '../src/renderer/editor';
import {newEvent} from '../src/renderer/document';
import {parseQtHtml,serializeQtHtml,plainText,markdown} from '../src/renderer/codec';
import {DocumentStore} from '../src/main/storage';
import {tableDomAttrs} from '../src/renderer/table-format';

// scripts/build-qt-compat.ps1 links Qt 6.8.3 and the sibling Qt project's
// libtlcore.a, so this harness only exists on a prepared developer machine.
const qtHarness = path.resolve('.cache/qt-compat/qt-compat.exe');
const hasQtHarness = existsSync(qtHarness);

let owner:TodoEditor;
const table='<table border="1" cellpadding="6" cellspacing="0" width="480" style="border-color:#3b82b6;border-style:solid"><tr><td colspan="2" bgcolor="#fff1b8" style="vertical-align:middle"><p><b>标题</b></p></td><td width="160"><p>甲</p></td></tr><tr><td rowspan="2" width="160"><p>跨行</p><p>次段</p></td><td width="160"><p>乙</p></td><td><p>丙</p></td></tr><tr><td><p>丁</p></td><td><p>戊</p></td></tr></table>';
function setup(html=table){const el=document.createElement('div');document.body.append(el);const change=vi.fn(),error=vi.fn();owner=new TodoEditor(el,{handle:'table',path:'table.tde',name:'table',revision:0,events:[{...newEvent(),id:1,content_html:html,content_text:'原始正文'}]},{change,error,selection:vi.fn(),asset:vi.fn()});owner.editor.view.setProps({handleScrollToSelection:()=>true});return {editor:owner.editor,change,error};}
function caret(text:string,offset=0){let found=-1;owner.editor.state.doc.descendants((n,p)=>{if(n.isText&&n.text===text)found=p+offset;});expect(found).toBeGreaterThan(-1);owner.editor.commands.setTextSelection(found);}
beforeAll(()=>{Range.prototype.getClientRects=()=>[] as unknown as DOMRectList;Range.prototype.getBoundingClientRect=()=>({left:0,top:0,right:0,bottom:0,width:0,height:0} as DOMRect);});
afterEach(()=>{owner?.destroy();document.body.innerHTML='';});
describe('Qt tables',()=>{
  it('writes legacy bgcolor as hex rather than CSS rgb notation',()=>{expect(tableDomAttrs({attributes:{bgcolor:'#fff1b8'}}).bgcolor).toBe('#fff1b8');expect(tableDomAttrs({attributes:{bgcolor:'rgb(255, 241, 184)'}}).bgcolor).toBe('#fff1b8');expect(serializeQtHtml(parseQtHtml(table).content)).toContain('bgcolor="#fff1b8"');});
  it('supports a row fully covered by a previous merged cell',()=>{const {editor}=setup('<table><tr><td rowspan="2" colspan="2">覆盖两行</td></tr><tr></tr></table>');editor.state.doc.check();expect(TableMap.get(editor.state.doc.firstChild!).problems).toBeNull();caret('覆盖两行',2);owner.split();editor.state.doc.descendants(n=>{if(n.type.name==='table')expect(TableMap.get(n).problems).toBeNull();});expect(editor.state.doc.textContent).toBe('覆盖两行');});
  it('splits nested tables while keeping each image and text on exactly one side',()=>{const {editor}=setup('<table><tr><td><p>外</p><table><tr><td><p>内<img src="asset:5" width="80" height="60" />文</p></td><td>后</td></tr></table></td><td>末</td></tr></table>');caret('文');owner.split();expect(editor.state.doc.textContent).toBe('外内文后末');let images=0;editor.state.doc.descendants(n=>{if(n.type.name==='table')expect(TableMap.get(n).problems).toBeNull();if(n.type.name==='image')images++;});expect(images).toBe(1);editor.commands.undo();expect(owner.records()).toHaveLength(1);});
  it.each([['标题',1],['甲',0],['跨行',1],['乙',0],['戊',1]] as const)('splits at %s/%s into valid grids without duplicating text, then undoes', (text,offset)=>{const {editor}=setup();const before=editor.state.doc.toJSON(),body=editor.state.doc.textContent;caret(text,offset);owner.split();editor.state.doc.check();expect(editor.state.doc.textContent).toBe(body);editor.state.doc.descendants(n=>{if(n.type.name==='table')expect(TableMap.get(n).problems).toBeNull();});expect(owner.records()).toHaveLength(2);for(const r of owner.records())expect(parseQtHtml(r.content_html).readOnly).toBe(false);editor.commands.undo();expect(editor.state.doc.toJSON()).toEqual(before);});
  it('imports spans, widths, backgrounds, vertical alignment and formatted paragraphs',()=>{const p=parseQtHtml(table);expect(p.readOnly).toBe(false);const t=p.content[0],cell=t.content![0].content![0];expect(t.type).toBe('table');expect(t.attrs?.layout.attributes.width).toBe('480');expect(cell.attrs).toMatchObject({colspan:2,rowspan:1,layout:{attributes:{bgcolor:'#fff1b8'},style:{'vertical-align':'middle'}}});expect(cell.content![0].content![0].marks).toContainEqual({type:'bold'});expect(parseQtHtml(serializeQtHtml(p.content)).readOnly).toBe(false);});
  it('selection and metadata changes leave original table bytes untouched',()=>{const {editor,change}=setup(),before=editor.state.doc.toJSON();caret('乙');editor.commands.selectAll();expect(editor.state.doc.toJSON()).toEqual(before);expect(change).not.toHaveBeenCalled();expect(TableMap.get(editor.state.doc.firstChild!).problems).toBeNull();owner.setEventDone(1,true);expect(owner.records()[0].content_html).toBe(table);});
  it('edits a cell then undo restores original HTML and topology',()=>{const {editor}=setup();caret('乙');editor.commands.insertContent('新');const html=owner.records()[0].content_html;expect(html).toContain('新乙');expect(html).toContain('rowspan="2"');expect(html).toContain('colspan="2"');editor.commands.undo();expect(owner.records()[0].content_html).toBe(table);});
  it.each(['rowBefore','rowAfter','columnBefore','columnAfter','deleteRow','deleteColumn','header'] as const)('%s keeps a rectangular table and undoes once',action=>{const {editor}=setup();caret('乙');const before=editor.state.doc.toJSON();expect(owner.tableAction(action)).toBe(true);editor.state.doc.check();expect(TableMap.get(editor.state.doc.firstChild!).problems).toBeNull();editor.commands.undo();expect(editor.state.doc.toJSON()).toEqual(before);});
  it('cell selection copies a rectangle and pastes over cells with one undo',async()=>{const {editor}=setup('<table><tr><td><p>A</p></td><td><p>B</p></td></tr><tr><td><p>C</p></td><td><p>D</p></td></tr></table>');const map=TableMap.get(editor.state.doc.firstChild!);editor.view.dispatch(editor.state.tr.setSelection(CellSelection.create(editor.state.doc,1+map.map[0],1+map.map[1])));let packet:any;window.desktop={copy:vi.fn(async p=>{packet=p;}),readClipboard:vi.fn(async()=>packet)} as any;await owner.copy();expect(packet.text).toBe('A\tB');editor.view.dispatch(editor.state.tr.setSelection(CellSelection.create(editor.state.doc,1+map.map[2],1+map.map[3])));await owner.paste();expect(editor.state.doc.textContent).toBe('ABAB');editor.commands.undo();expect(editor.state.doc.textContent).toBe('ABCD');});
  it('merges and splits selected cells without losing their text',()=>{const {editor}=setup('<table><tr><td>A</td><td>B</td></tr></table>'),map=TableMap.get(editor.state.doc.firstChild!);editor.view.dispatch(editor.state.tr.setSelection(CellSelection.create(editor.state.doc,1+map.map[0],1+map.map[1])));expect(owner.tableAction('merge')).toBe(true);expect(editor.state.doc.firstChild!.firstChild!.childCount).toBe(1);expect(editor.state.doc.textContent).toBe('AB');expect(owner.tableAction('split')).toBe(true);expect(editor.state.doc.firstChild!.firstChild!.childCount).toBe(2);expect(editor.state.doc.textContent).toBe('AB');});
  it.each(['<table><tr><td rowspan="3">bad</td></tr></table>','<table><tr><td>A</td><td>B</td></tr><tr><td>C</td></tr></table>','<table style="float:left"><tr><td>float</td></tr></table>','<table style="-qt-table-type:root"><tr><td>frame</td></tr></table>'])('preserves unsupported table layout read-only: %s',html=>{expect(parseQtHtml(html).readOnly).toBe(true);const {editor}=setup(html);expect(editor.state.doc.firstChild?.type.name).toBe('legacy');editor.commands.selectAll();editor.commands.deleteSelection();expect(owner.records()[0].content_html).toBe(html);});
  it('exports Markdown as HTML to retain merged cells, and plain text separates cells',()=>{const parsed=parseQtHtml(table);expect(markdown(parsed.content)).toContain('<table');expect(markdown(parsed.content)).toContain('rowspan="2"');expect(plainText(parsed.content)).toContain('标题\t甲');expect(plainText(parsed.content)).toContain('跨行 / 次段\t乙\t丙');});
  it.skipIf(!hasQtHarness)('retains actual Qt table topology and layout through two Qt saves',async()=>{const root=mkdtempSync(path.join(os.tmpdir(),'todoline-tables-')),file=path.join(root,'table.tde'),input=path.join(root,'table.html'),store=new DocumentStore(),opened:string[]=[];const open=()=>{const d=store.open(file);opened.push(d.handle);return d;};writeFileSync(input,'<p>表格前</p>'+table+'<p>表格后</p>');const env={...process.env,QT_QPA_PLATFORM:'offscreen',PATH:'E:\\Qt\\6.8.3\\mingw_64\\bin;E:\\Qt\\Tools\\mingw1310_64\\bin;'+process.env.PATH};const qt=(mode:string)=>execFileSync(path.resolve('.cache/qt-compat/qt-compat.exe'),[mode,file,input],{env,windowsHide:true});
    try{qt('create-html');for(let i=0;i<2;i++){const doc=open(),parsed=parseQtHtml(doc.events[0].content_html);expect(parsed.readOnly,parsed.reason).toBe(false);const t=parsed.content.find(n=>n.type==='table')!;expect(t.attrs?.layout.attributes.width).toBe('480');expect(t.content!.length).toBe(3);expect(t.content![0].content![0].attrs?.colspan).toBe(2);expect(t.content![1].content![0].attrs?.rowspan).toBe(2);await store.save({...doc,events:doc.events.map(e=>({...e,content_html:serializeQtHtml(parsed.content),content_text:plainText(parsed.content)}))});store.close(doc.handle);qt('edit');}const final=open();expect(final.events[0].content_text).toContain('跨行');expect(final.events[0].content_html).toContain('vertical-align:middle');expect(final.events[0].content_html).toContain('#fff1b8');store.close(final.handle);}finally{for(const handle of opened)try{store.close(handle);}catch{}if(!root.startsWith(path.resolve(os.tmpdir())+path.sep))throw new Error('Unexpected test path');rmSync(root,{recursive:true,force:true});}
  });
});
