// @vitest-environment jsdom
import {afterEach,beforeAll,expect,it,vi} from 'vitest';
import {Selection} from '@tiptap/pm/state';
import {TableMap} from '@tiptap/pm/tables';
import {TodoEditor} from '../src/renderer/editor';
import {newEvent} from '../src/renderer/document';
import {TableRowSelection} from '../src/renderer/table-row-selection';
import {lineRows} from '../src/renderer/line-gutter';
import {parseQtHtml} from '../src/renderer/codec';
let owner:TodoEditor;
const html='<table width="400" border="1"><tr><td><b>A</b></td><td>B</td></tr><tr><td>C</td><td>D</td></tr><tr><td>E</td><td>F</td></tr><tr><td>G</td><td>H</td></tr></table><p>尾部</p>';
function setup(source=html){const element=document.createElement('div');document.body.append(element);const error=vi.fn();owner=new TodoEditor(element,{handle:'rows',path:'rows.tde',name:'rows',revision:0,events:[{...newEvent(),id:1,top_divider:0,content_html:source,content_text:'表格'}]},{change:vi.fn(),selection:vi.fn(),error,asset:vi.fn()});owner.editor.view.setProps({handleScrollToSelection:()=>true});return {editor:owner.editor,error};}
function choose(index:number,mode='replace'){(owner as any).chooseRow(lineRows(owner.editor.state.doc).filter(r=>r.kind==='table')[index],mode);}
function selected(){const s=owner.editor.state.selection;expect(s).toBeInstanceOf(TableRowSelection);return s as TableRowSelection;}
beforeAll(()=>{Range.prototype.getClientRects=()=>[] as unknown as DOMRectList;Range.prototype.getBoundingClientRect=()=>({left:0,top:0,right:0,bottom:0,width:0,height:0} as DOMRect);});
afterEach(()=>{owner?.destroy();document.body.innerHTML='';});
it('Ctrl selects and toggles exact rows while preserving original HTML',()=>{setup();choose(0);choose(2,'toggle');expect(selected().rows).toEqual([0,2]);expect(selected().content().content.firstChild!.textContent).toBe('ABEF');expect(owner.records()[0].content_html).toBe(html);choose(0,'toggle');expect(selected().rows).toEqual([2]);choose(2,'toggle');expect(owner.editor.state.selection.empty).toBe(true);});
it('Shift extends from the latest toggle and Ctrl drag only adds visited rows',()=>{setup();choose(0);choose(2,'toggle');choose(3,'extend');expect(selected().rows).toEqual([2,3]);choose(0,'add');expect(selected().rows).toEqual([0,2,3]);});
it('Delete clears only selected cells, keeps the grid and undoes as one edit',()=>{const {editor}=setup();choose(0);choose(2,'toggle');editor.commands.deleteSelection();expect(editor.state.doc.textContent).toBe('CDGH尾部');expect(TableMap.get(editor.state.doc.firstChild!).height).toBe(4);editor.commands.undo();expect(owner.records()[0].content_html).toBe(html);expect(selected().rows).toEqual([0,2]);});
it('delete-row command removes only selected rows and restores their format on undo',()=>{const {editor}=setup();choose(0);choose(2,'toggle');expect(owner.tableAction('deleteRow')).toBe(true);expect(editor.state.doc.textContent).toBe('CDGH尾部');expect(TableMap.get(editor.state.doc.firstChild!).height).toBe(2);editor.commands.undo();expect(owner.records()[0].content_html).toBe(html);});
it('all selected rows can be removed without losing surrounding content',()=>{const {editor}=setup();choose(0);choose(3,'extend');owner.tableAction('deleteRow');expect(editor.state.doc.firstChild!.type.name).toBe('paragraph');expect(editor.state.doc.textContent).toBe('尾部');editor.commands.undo();expect(owner.records()[0].content_html).toBe(html);});
it('rowspan closure is transitive and toggles the entire connected group',()=>{setup('<table><tr><td rowspan="2">A</td><td>B</td></tr><tr><td rowspan="2">C</td></tr><tr><td>D</td></tr><tr><td>E</td><td>F</td></tr></table>');choose(0);expect(selected().rows).toEqual([0,1,2]);choose(3,'toggle');expect(selected().rows).toEqual([0,1,2,3]);choose(1,'toggle');expect(selected().rows).toEqual([3]);});
it('copied merged rows and the remaining rows both form valid tables',async()=>{const {editor}=setup('<table><tr><td rowspan="2">A</td><td>B</td></tr><tr><td>C</td></tr><tr><td>D</td><td>E</td></tr><tr><td colspan="2">F</td></tr></table>');choose(0);choose(3,'toggle');const table=selected().content().content.firstChild!;expect(TableMap.get(table).problems).toBeNull();expect(table.textContent).toBe('ABCF');owner.tableAction('deleteRow');expect(editor.state.doc.textContent).toBe('DE');expect(TableMap.get(editor.state.doc.firstChild!).problems).toBeNull();});
it('copy and cut include rich formatting of selected rows without intervening cells',async()=>{const {editor}=setup();let packet:any;window.desktop={copy:vi.fn(async p=>{packet=p;})} as any;choose(0);choose(2,'toggle');await owner.copy(false,true);expect(packet.text).toBe('A\tB\nE\tF');expect(packet.html).toContain('<strong>A</strong>');expect(packet.html).not.toContain('>C<');expect(parseQtHtml(packet.html).readOnly).toBe(false);expect(editor.state.doc.textContent).toBe('CDGH尾部');editor.commands.undo();expect(owner.records()[0].content_html).toBe(html);});
it('formatting changes only selected paragraphs and preserves intervening rows',()=>{const {editor}=setup();choose(0);choose(2,'toggle');owner.formatParagraphs(f=>({...f,textAlign:'center'}));const table=editor.state.doc.firstChild!;expect(table.child(0).firstChild!.firstChild!.attrs.format.textAlign).toBe('center');expect(table.child(1).firstChild!.firstChild!.attrs.format).toBeNull();expect(table.child(2).firstChild!.firstChild!.attrs.format.textAlign).toBe('center');});
it('nonrectangular merge is rejected instead of merging unselected cells',()=>{const {error}=setup();choose(0);choose(2,'toggle');expect(owner.tableAction('merge')).toBe(false);expect(error).toHaveBeenCalledWith(expect.stringContaining('连续'));expect(owner.records()[0].content_html).toBe(html);});
it('bookmarks map across content edits and document insertions',()=>{const {editor}=setup();choose(0);choose(2,'toggle');const before=selected(),tr=editor.state.tr.insert(0,editor.schema.nodes.paragraph.create(null,editor.schema.text('前置')));editor.view.dispatch(tr);expect(selected().rows).toEqual([0,2]);expect(selected().tablePos).toBe(4);expect(before.getBookmark().map(tr.mapping).resolve(tr.doc).eq(selected())).toBe(true);expect(Selection.fromJSON(tr.doc,selected().toJSON()).eq(selected())).toBe(true);});
it('a deleted table bookmark falls back to a valid caret',()=>{const {editor}=setup();choose(0);const s=selected(),tr=editor.state.tr.delete(0,editor.state.doc.firstChild!.nodeSize);expect(s.map(tr.doc,tr.mapping).empty).toBe(true);});
it('rich table paste fills chosen rows in order and leaves the skipped row byte-identical',async()=>{const {editor}=setup();const middle=editor.state.doc.firstChild!.child(1).toJSON();window.desktop={readClipboard:vi.fn(async()=>({html:'<table><tr><td><i>一</i></td><td>二</td></tr><tr><td>三</td><td>四</td></tr></table>',text:''}))} as any;choose(0);choose(2,'toggle');await owner.paste();expect(editor.state.doc.textContent).toBe('一二CD三四GH尾部');expect(editor.state.doc.firstChild!.child(1).toJSON()).toEqual(middle);expect(selected().rows).toEqual([0,2]);editor.commands.undo();expect(owner.records()[0].content_html).toBe(html);});
it('a pasted rowspan crossing a gap splits at the gap without duplicating its body',async()=>{const {editor}=setup();window.desktop={readClipboard:vi.fn(async()=>({html:'<table><tr><td rowspan="2">合并</td><td>甲</td></tr><tr><td>乙</td></tr></table>',text:''}))} as any;choose(0);choose(2,'toggle');await owner.paste();expect(editor.state.doc.textContent).toBe('合并甲CD乙GH尾部');expect(TableMap.get(editor.state.doc.firstChild!).problems).toBeNull();expect(editor.state.doc.firstChild!.child(0).firstChild!.attrs.rowspan).toBe(1);expect(editor.state.doc.firstChild!.child(2).firstChild!.textContent).toBe('');});
it('plain paste follows cell tiling semantics without overwriting the middle row',async()=>{const {editor}=setup();window.desktop={readClipboard:vi.fn(async()=>({text:'替换'}))} as any;choose(0);choose(2,'toggle');await owner.paste();expect(editor.state.doc.textContent).toBe('替换替换CD替换替换GH尾部');editor.commands.undo();expect(owner.records()[0].content_html).toBe(html);});
it('a failed clipboard write leaves every selected cell and the selection intact',async()=>{const {error}=setup();window.desktop={copy:vi.fn(async()=>{throw new Error('写入失败');})} as any;choose(0);choose(2,'toggle');await owner.copy(false,true);expect(owner.records()[0].content_html).toBe(html);expect(selected().rows).toEqual([0,2]);expect(error).toHaveBeenCalled();});
it('delayed cut refuses to remove changed selected contents',async()=>{const {editor,error}=setup();let release!:()=>void;window.desktop={copy:vi.fn(()=>new Promise<void>(r=>release=r))} as any;choose(0);choose(2,'toggle');const copy=owner.copy(false,true);await vi.waitFor(()=>expect(release).toBeTypeOf('function'));editor.view.dispatch(editor.state.tr.insertText('新',selected().ranges[0].$from.pos+1));release();await copy;expect(editor.state.doc.textContent).toContain('新A');expect(error).toHaveBeenCalledWith(expect.stringContaining('修改'));});
it('delayed cut permits an unrelated row edit and preserves the new text',async()=>{const {editor,error}=setup();let release!:()=>void;window.desktop={copy:vi.fn(()=>new Promise<void>(r=>release=r))} as any;choose(0);choose(2,'toggle');const copy=owner.copy(false,true);await vi.waitFor(()=>expect(release).toBeTypeOf('function'));let pos=0;editor.state.doc.descendants((n,p)=>{if(n.isText&&n.text==='C')pos=p;});editor.view.dispatch(editor.state.tr.insertText('新',pos));release();await copy;expect(editor.state.doc.textContent).toBe('新CDGH尾部');expect(error).not.toHaveBeenCalled();});
