import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import {ChevronUp,ChevronDown,X,GitCompareArrows} from 'lucide-react';
import type {DocumentTab} from './runtime';
import type {DiffCell,DiffResult} from './diff-engine';
import {diffDocument} from './diff-document';
import './diff-view.css';

function Content({cell}:{cell:DiffCell}){
 const parts:React.ReactNode[]=[];let offset=0;
 for(const [start,end] of cell.ranges){if(start>offset)parts.push(cell.text.slice(offset,start));parts.push(<mark key={start}>{cell.text.slice(start,end)}</mark>);offset=end;}
 parts.push(cell.text.slice(offset));return <>{parts}</>;
}
export default function DiffView({left,right,onClose,fontSize}:{left:DocumentTab;right:DocumentTab;onClose:()=>void;fontSize:number}){
 const [result,setResult]=useState<DiffResult|null>(null),[error,setError]=useState(''),[current,setCurrent]=useState(0),[viewport,setViewport]=useState({top:0,height:600});
 const dialog=useRef<HTMLDivElement>(null),leftPane=useRef<HTMLDivElement>(null),rightPane=useRef<HTMLDivElement>(null),frame=useRef(0);
 const synchronized=useRef(new WeakMap<HTMLElement,number>());
 const rowHeight=Math.ceil(fontSize*1.7)+2;
 useEffect(()=>{
  let cancelled=false,worker:Worker|undefined;
  void Promise.all([left.whenReady(),right.whenReady()]).then(()=>{
   if(cancelled)return;worker=new Worker(new URL('./diff-worker.ts',import.meta.url),{type:'module'});
   worker.onmessage=(event:MessageEvent<{result?:DiffResult;error?:string}>)=>{if(!cancelled){if(event.data.result)setResult(event.data.result);else setError(event.data.error??'对比失败');}worker?.terminate();};
   worker.onerror=()=>{if(!cancelled)setError('对比计算失败，请关闭后重试。');worker?.terminate();};
   worker.postMessage({left:diffDocument(left),right:diffDocument(right)});
  }).catch(error=>{if(!cancelled)setError(String(error));});
  return()=>{cancelled=true;worker?.terminate();};
 },[left,right]);
 useEffect(()=>{
  const previous=document.activeElement as HTMLElement|null;dialog.current?.focus({preventScroll:true});
  // Keep native window controls usable while preventing edits behind the comparison.
  const background=Array.from(document.querySelectorAll<HTMLElement>('.app > :not(.titlebar)')).map(element=>({element,inert:element.inert}));
  for(const {element} of background)element.inert=true;
  return()=>{for(const {element,inert} of background)element.inert=inert;if(previous?.isConnected)previous.focus({preventScroll:true});};
 },[]);
 const scrollTo=(index:number)=>{const row=result?.changes[index];if(row===undefined)return;cancelAnimationFrame(frame.current);frame.current=0;setCurrent(index);const top=Math.max(0,(row-3)*rowHeight);for(const pane of [leftPane.current,rightPane.current])if(pane){pane.scrollTop=top;synchronized.current.set(pane,pane.scrollTop);}setViewport(v=>({...v,top:leftPane.current?.scrollTop??top}));};
 useLayoutEffect(()=>{if(result?.changes.length)scrollTo(0);},[result]);
 const step=(delta:number)=>{if(result?.changes.length)scrollTo((current+delta+result.changes.length)%result.changes.length);};
 useEffect(()=>{
  const key=(event:KeyboardEvent)=>{
   if(event.isComposing)return;
   if(event.key==='Escape'){event.preventDefault();event.stopImmediatePropagation();onClose();}
   else if(event.key==='F7'||event.key==='F3'){event.preventDefault();event.stopImmediatePropagation();step(event.shiftKey?-1:1);}
   else if(event.key==='Tab'){
    const controls=Array.from(dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),[tabindex="0"]')??[]);if(!controls.length)return;
    const at=controls.indexOf(document.activeElement as HTMLElement),next=(at+(event.shiftKey?-1:1)+controls.length)%controls.length;event.preventDefault();controls[next].focus();
   }
  };window.addEventListener('keydown',key,true);return()=>window.removeEventListener('keydown',key,true);
 });
 useLayoutEffect(()=>{
  const el=leftPane.current;if(!el)return;const observer=new ResizeObserver(()=>setViewport(v=>({...v,height:el.clientHeight})));observer.observe(el);setViewport(v=>({...v,height:el.clientHeight}));
  return()=>{observer.disconnect();cancelAnimationFrame(frame.current);};
 },[]);
 const onScroll=(el:HTMLDivElement,other:HTMLDivElement|null)=>{
  const top=el.scrollTop,expected=synchronized.current.get(el);synchronized.current.delete(el);
  // Ignore scroll events generated by the other pane or a difference jump.
  if(expected!==undefined&&expected===top)return;
  if(other&&other.scrollTop!==top){other.scrollTop=top;synchronized.current.set(other,other.scrollTop);}
  if(frame.current)cancelAnimationFrame(frame.current);frame.current=requestAnimationFrame(()=>{frame.current=0;setViewport(v=>({...v,top}));});
 };
 const start=Math.max(0,Math.floor(viewport.top/rowHeight)-6),end=Math.min(result?.rows.length??0,Math.ceil((viewport.top+viewport.height)/rowHeight)+6);
 const pane=(side:'left'|'right',tab:DocumentTab)=><section className="diff-pane">
  <div className="diff-file" title={tab.snapshot.path}><span>{side==='left'?'前一个标签':'当前标签'}</span><strong>{tab.snapshot.name}</strong></div>
  <div className="diff-scroll" aria-label={side==='left'?'前一个文件内容':'当前文件内容'} tabIndex={0} ref={side==='left'?leftPane:rightPane} onScroll={e=>onScroll(e.currentTarget,side==='left'?rightPane.current:leftPane.current)}>
   <div className="diff-space" style={{height:(result?.rows.length??0)*rowHeight,minWidth:`calc(${side==='left'?result?.leftColumns??0:result?.rightColumns??0}ch + 88px)`}}>
    {result?.rows.slice(start,end).map((row,offset)=>{const index=start+offset,cell=row[side],active=!!result.changes.length&&index>=result.changes[current]&&index<(result.changes[current+1]??result.rows.length)&&row.kind!=='equal';
     return <div key={index} data-diff-row={index} data-kind={cell?row.kind:'gap'} data-current={active?'':undefined} className={'diff-line diff-'+(cell?row.kind:'gap')+(active?' diff-current':'')} style={{top:index*rowHeight,height:rowHeight,lineHeight:rowHeight+'px'}}>
      <span className="diff-number" aria-hidden="true"><span>{cell?.line??''}</span><i>{!cell?'':row.kind==='add'?'+':row.kind==='delete'?'−':row.kind==='change'?'~':''}</i></span>
      <span className="diff-text">{cell?<Content cell={cell}/>:null}</span>
     </div>;
    })}
   </div>
  </div>
 </section>;
 return <div className="diff-backdrop"><div ref={dialog} className="diff-view" role="dialog" aria-modal="true" aria-label="文件差异对比" tabIndex={-1} style={{fontSize}} onCopy={event=>{const selection=window.getSelection();if(selection&&!selection.isCollapsed){event.preventDefault();event.clipboardData.setData('text/plain',selection.toString());}}}>
  <header className="diff-header"><GitCompareArrows size={18}/><strong>Compare</strong><span className="diff-mode">从左侧修改到右侧，需：</span><div className="diff-summary" aria-live="polite">{error?'对比失败':!result?'正在对比…':result.changes.length?<><span className="diff-added-count">新增 {result.added} 行</span><span className="diff-deleted-count">删除 {result.deleted} 行</span><span>修改 {result.modified} 行</span></>:'内容一致，无差异'}</div>
   <span className="diff-position">{result?.changes.length?`${current+1} / ${result.changes.length} 处`:''}</span>
   <button aria-label="上一个差异" title="上一个差异 · Shift+F7" disabled={!result?.changes.length} onClick={()=>step(-1)}><ChevronUp size={17}/></button>
   <button aria-label="下一个差异" title="下一个差异 · F7" disabled={!result?.changes.length} onClick={()=>step(1)}><ChevronDown size={17}/></button>
   <button aria-label="关闭对比" title="关闭对比 · Esc" onClick={onClose}><X size={18}/></button>
  </header>
  {error&&<p className="diff-message" role="alert">{error}</p>}
  <div className="diff-panes">{pane('left',left)}{pane('right',right)}</div>
 </div></div>;
}
